# Generated by Django 5.2.7 on 2025-11-23 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GermanExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('GOETHE', 'Goethe-Zertifikat'), ('TELC', 'telc Deutsch'), ('TESTDAF', 'TestDaF'), ('DSH', 'DSH'), ('GENERAL', 'Général / Visa')], default='GENERAL', max_length=20)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GermanLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skill', models.CharField(choices=[('HOREN', 'Hören (Compréhension orale)'), ('LESEN', 'Lesen (Compréhension écrite)'), ('SPRECHEN', 'Sprechen (Expression orale)'), ('SCHREIBEN', 'Schreiben (Expression écrite)'), ('GRAMMATIK', 'Grammatik'), ('WORTSCHATZ', 'Wortschatz (Vocabulaire)')], default='GRAMMATIK', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('intro', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Contenu de la leçon (texte, explications, exemples). Tu peux mettre du HTML simple ou du Markdown.')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='GermanPrepApp.germanexam')),
            ],
            options={
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GermanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(blank=True, max_length=255)),
                ('option_d', models.CharField(blank=True, max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='GermanPrepApp.germanlesson')),
            ],
        ),
        migrations.CreateModel(
            name='GermanTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='GermanPrepApp.germanexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='german_test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GermanUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GermanPrepApp.germanexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='GermanPrepApp.germantestsession')),
            ],
        ),
        migrations.CreateModel(
            name='GermanUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('best_score', models.FloatField(default=0)),
                ('badges', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='german_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
