# Generated by Django 5.2.7 on 2025-11-24 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GermanPrepApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GermanPlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(blank=True, max_length=255)),
                ('option_d', models.CharField(blank=True, max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='germanuserprofile',
            name='placement_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='germanuserprofile',
            name='placement_score',
            field=models.FloatField(blank=True, help_text='Score (%) obtenu au dernier test de placement.', null=True),
        ),
        migrations.CreateModel(
            name='GermanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF (cours / exercices)'), ('VIDEO', 'Vidéo'), ('LINK', 'Lien / article'), ('AUDIO', 'Audio / podcast'), ('OTHER', 'Autre')], default='PDF', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(help_text='Lien vers le PDF / vidéo / ressource (Drive, YouTube, site externe...).')),
                ('exam', models.ForeignKey(blank=True, help_text='Laisse vide si la ressource ne dépend que de la leçon.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='GermanPrepApp.germanexam')),
                ('lesson', models.ForeignKey(blank=True, help_text='Optionnel. Pour lier une ressource à une leçon précise.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='GermanPrepApp.germanlesson')),
            ],
        ),
    ]
