# Generated by Django 5.2.7 on 2025-12-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GermanPrepApp', '0002_germanplacementquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='germantestsession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Temps total passé sur le test (en secondes).'),
        ),
    ]
