# Generated by Django 5.2.7 on 2026-04-11 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueGaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('couleur', models.CharField(default='#FF6B00', help_text='Couleur hex de la marque', max_length=7)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marque de gaz',
                'verbose_name_plural': 'Marques de gaz',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='QuartierGaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='VilleGaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('region', models.CharField(default='Centre', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='DepotGaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gaz/depots/')),
                ('adresse', models.CharField(blank=True, max_length=250)),
                ('zone_livraison', models.TextField(blank=True, help_text='Quartiers desservis par la livraison')),
                ('telephone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='Numero WhatsApp sans +, ex: 237680625082', max_length=20)),
                ('whatsapp_msg', models.CharField(blank=True, max_length=300)),
                ('tailles', models.JSONField(blank=True, default=list, help_text='Ex: ["6kg","12kg","15kg"]')),
                ('prix_6kg', models.PositiveIntegerField(blank=True, null=True)),
                ('prix_12kg', models.PositiveIntegerField(blank=True, null=True)),
                ('prix_15kg', models.PositiveIntegerField(blank=True, null=True)),
                ('livraison_rapide', models.BooleanField(default=True)),
                ('delai_livraison', models.CharField(default='30-60 min', max_length=60)),
                ('horaires', models.CharField(default='Lun-Sam 7h-20h', max_length=150)),
                ('livraison_nuit', models.BooleanField(default=False)),
                ('paiement_info', models.CharField(default='Paiement a la livraison (especes)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('nb_avis', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gerant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_gaz', to=settings.AUTH_USER_MODEL)),
                ('marques', models.ManyToManyField(blank=True, related_name='depots', to='gaz.marquegaz')),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots', to='gaz.quartiergaz')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='gaz.villegaz')),
            ],
            options={
                'verbose_name': 'Depot de gaz',
                'verbose_name_plural': 'Depots de gaz',
                'ordering': ['-is_featured', '-is_verified', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='quartiergaz',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='gaz.villegaz'),
        ),
        migrations.CreateModel(
            name='AvisDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_gaz', to=settings.AUTH_USER_MODEL)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='gaz.depotgaz')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('depot', 'auteur')},
            },
        ),
    ]
