# Generated by Django 5.2.7 on 2026-04-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotgaz',
            name='abonnement_actif',
            field=models.BooleanField(default=False, help_text='Le depot a paye son abonnement — visible sur la plateforme'),
        ),
        migrations.AddField(
            model_name='depotgaz',
            name='abonnement_expire_le',
            field=models.DateField(blank=True, help_text="Date d'expiration de l'abonnement", null=True),
        ),
        migrations.AddField(
            model_name='depotgaz',
            name='montant_paye',
            field=models.PositiveIntegerField(blank=True, help_text='Montant recu en FCFA', null=True),
        ),
        migrations.AddField(
            model_name='depotgaz',
            name='notes_admin',
            field=models.TextField(blank=True, help_text='Notes internes (paiements, historique...)'),
        ),
        migrations.AddField(
            model_name='depotgaz',
            name='plan_actif',
            field=models.CharField(blank=True, choices=[('basic', 'Basic — 2 000 FCFA/mois'), ('pro', 'Pro — 5 000 FCFA/mois'), ('premium', 'Premium — 10 000 FCFA/mois')], max_length=10, null=True, verbose_name='Plan souscrit'),
        ),
        migrations.AddField(
            model_name='depotgaz',
            name='ref_paiement',
            field=models.CharField(blank=True, help_text='Reference Orange Money / MTN / etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='depotgaz',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Activer apres confirmation du paiement'),
        ),
    ]
