# Generated by Django 6.0.2 on 2026-03-21 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0001_initial'),
        ('formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type_coupon', models.CharField(choices=[('pourcent', 'Pourcentage de réduction'), ('fixe', 'Montant fixe'), ('gratuit', 'Accès gratuit')], default='pourcent', max_length=10)),
                ('valeur', models.DecimalField(decimal_places=2, default=0, help_text='Valeur (% ou FCFA selon le type)', max_digits=8)),
                ('max_utilisations', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('nb_utilisations', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('type_tx', models.CharField(choices=[('achat_cours', 'Achat formation'), ('achat_produit', 'Achat produit boutique'), ('abonnement', 'Abonnement Pro/Enterprise'), ('service', 'Paiement service'), ('remboursement', 'Remboursement')], max_length=20)),
                ('methode', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('orange', 'Orange Money'), ('carte', 'Carte bancaire'), ('virement', 'Virement bancaire'), ('gratuit', 'Gratuit (coupon)')], default='mtn_momo', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='XAF', max_length=5)),
                ('telephone', models.CharField(blank=True, help_text='Numéro Mobile Money', max_length=25)),
                ('statut', models.CharField(choices=[('initie', 'Initié'), ('en_attente', 'En attente de confirmation'), ('succes', 'Succès'), ('echec', 'Échec'), ('expire', 'Expiré'), ('rembourse', 'Remboursé')], default='initie', max_length=20)),
                ('ref_operateur', models.CharField(blank=True, help_text="Référence de l'opérateur MTN/Airtel", max_length=200)),
                ('ref_interne', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('erreur', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='boutique.commande')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='formations.formation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
