# Generated by Django 6.0.2 on 2026-03-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_tx',
            field=models.CharField(choices=[('achat_cours', 'Achat formation'), ('achat_produit', 'Achat produit boutique'), ('abonnement', 'Abonnement Pro/Enterprise'), ('service', 'Paiement service'), ('remboursement', 'Remboursement'), ('premium_marketplac', 'Pack Premium marketplace'), ('boost_annonce', 'Boost annonce/bien/véhicule')], max_length=20),
        ),
    ]
