# Generated by Django 5.2.7 on 2026-04-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_planpremiumapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpremiumapp',
            name='benefices',
            field=models.JSONField(default=list, help_text='Liste JSON des bénéfices. Ex: ["30 jours Premium","Annonces illimitées"]', verbose_name='Bénéfices'),
        ),
        migrations.AlterField(
            model_name='planpremiumapp',
            name='slug',
            field=models.SlugField(help_text='ex: starter, pro, expert — sans espaces', max_length=30, verbose_name='Identifiant'),
        ),
    ]
