# Generated by Django 6.0.2 on 2026-03-24 07:58

import annonces_cam.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('devise', models.CharField(choices=[('XAF', 'XAF (FCFA)'), ('EUR', 'EUR (€)'), ('USD', 'USD ($)')], default='XAF', max_length=5)),
                ('prix_a_debattre', models.BooleanField(default=False)),
                ('gratuit', models.BooleanField(default=False)),
                ('etat_produit', models.CharField(choices=[('NEUF', 'Neuf'), ('COMME_NEUF', 'Comme neuf'), ('BON_ETAT', 'Bon état'), ('ETAT_CORRECT', 'État correct'), ('POUR_PIECES', 'Pour pièces'), ('NON_APPLICABLE', 'Non applicable (service)')], default='BON_ETAT', max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('adresse_precise', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('telephone_contact', models.CharField(max_length=20)),
                ('whatsapp_contact', models.CharField(blank=True, max_length=20)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('mode_contact', models.CharField(choices=[('TELEPHONE', 'Téléphone uniquement'), ('WHATSAPP', 'WhatsApp uniquement'), ('MESSAGE_INTERNE', 'Message interne'), ('TOUS', 'Tous les modes')], default='TOUS', max_length=20)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('PUBLIEE', 'Publiée'), ('EXPIREE', 'Expirée'), ('VENDUE', 'Vendue'), ('SUSPENDUE', 'Suspendue'), ('REFUSEE', 'Refusée'), ('ARCHIVEE', 'Archivée')], default='EN_ATTENTE_VALIDATION', max_length=25)),
                ('est_mise_en_avant', models.BooleanField(default=False)),
                ('est_urgente', models.BooleanField(default=False)),
                ('est_coup_de_coeur', models.BooleanField(default=False)),
                ('publiee_par_admin', models.BooleanField(default=False)),
                ('note_admin', models.TextField(blank=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('vues', models.IntegerField(default=0)),
                ('nombre_contacts', models.IntegerField(default=0)),
                ('nombre_favoris', models.IntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_derniere_remontee', models.DateTimeField(blank=True, null=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-est_mise_en_avant', '-date_publication', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoostAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_boost', models.CharField(choices=[('REMONTEE_TOP', 'Remontée en tête'), ('MISE_EN_AVANT_7J', 'Mise en avant 7 jours'), ('MISE_EN_AVANT_15J', 'Mise en avant 15 jours'), ('MISE_EN_AVANT_30J', 'Mise en avant 30 jours'), ('BADGE_URGENT', 'Badge Urgent 7 jours'), ('PACK_COMPLET', 'Pack Complet 30 jours')], max_length=25)),
                ('prix_paye', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('est_actif', models.BooleanField(default=False)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='annonces_cam.annonce')),
            ],
            options={
                'verbose_name': 'Boost annonce',
                'verbose_name_plural': 'Boosts annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icone', models.CharField(default='fa-tag', max_length=60)),
                ('couleur_hex', models.CharField(default='#607D8B', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('est_active', models.BooleanField(default=True)),
                ('est_vedette', models.BooleanField(default=False)),
                ('nombre_annonces', models.IntegerField(default=0)),
                ('image_banniere', models.ImageField(blank=True, null=True, upload_to='annonces/categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='annonces_cam.categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='annonce',
            name='categorie',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='annonces', to='annonces_cam.categorie'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='sous_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_sous_cat', to='annonces_cam.categorie'),
        ),
        migrations.CreateModel(
            name='AlerteAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mots_cles', models.CharField(blank=True, max_length=200)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('prix_max', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('etat_produit', models.CharField(blank=True, choices=[('NEUF', 'Neuf'), ('COMME_NEUF', 'Comme neuf'), ('BON_ETAT', 'Bon état'), ('ETAT_CORRECT', 'État correct'), ('POUR_PIECES', 'Pour pièces'), ('NON_APPLICABLE', 'Non applicable (service)')], max_length=20)),
                ('frequence', models.CharField(choices=[('IMMEDIAT', 'Immédiat (à chaque nouvelle annonce)'), ('QUOTIDIEN', 'Quotidien (résumé du jour)'), ('HEBDOMADAIRE', 'Hebdomadaire')], default='QUOTIDIEN', max_length=15)),
                ('est_active', models.BooleanField(default=True)),
                ('derniere_notification', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_annonces', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonces_cam.categorie')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
            },
        ),
        migrations.CreateModel(
            name='ConversationAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_acheteur', to=settings.AUTH_USER_MODEL)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='annonces_cam.annonce')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_vendeur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='FavoriAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='annonces_cam.annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_annonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
            },
        ),
        migrations.CreateModel(
            name='MessageAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=1000)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='annonces_cam.conversationannonce')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus_annonce', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes_annonce', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=annonces_cam.models.photo_upload_path)),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('est_photo_principale', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='annonces_cam.annonce')),
            ],
            options={
                'verbose_name': 'Photo annonce',
                'verbose_name_plural': 'Photos annonces',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfilVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(blank=True, max_length=150)),
                ('description_boutique', models.TextField(blank=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='annonces/profils/')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('compte_type', models.CharField(choices=[('GRATUIT', 'Gratuit (5 annonces)'), ('PREMIUM', 'Premium (illimité)')], default='GRATUIT', max_length=10)),
                ('date_expiration_premium', models.DateField(blank=True, null=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('note_moyenne', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('nombre_avis', models.IntegerField(default=0)),
                ('nombre_ventes_reussies', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_vendeur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil vendeur',
                'verbose_name_plural': 'Profils vendeurs',
            },
        ),
        migrations.CreateModel(
            name='RemonteeAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remontees', to='annonces_cam.annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remontée',
                'verbose_name_plural': 'Remontées',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalementAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('FAUSSE_ANNONCE', 'Annonce fausse / trompeuse'), ('ARNAQUE', 'Arnaque / Fraude'), ('PRODUIT_INTERDIT', 'Produit interdit'), ('PRIX_ABUSIF', 'Prix abusif'), ('CONTENU_INAPPROPRIE', 'Contenu inapproprié'), ('DOUBLON', 'Annonce en double'), ('AUTRE', 'Autre')], max_length=25)),
                ('description', models.TextField()),
                ('traite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='annonces_cam.annonce')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvisVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='annonces_cam.annonce')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis vendeur',
                'verbose_name_plural': 'Avis vendeurs',
                'unique_together': {('vendeur', 'acheteur', 'annonce')},
            },
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['statut', 'date_expiration'], name='annonces_ca_statut_cd586b_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['categorie', 'statut'], name='annonces_ca_categor_a203e3_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['ville', 'statut'], name='annonces_ca_ville_2dbc89_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['vendeur', 'statut'], name='annonces_ca_vendeur_8f1685_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationannonce',
            unique_together={('annonce', 'acheteur')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriannonce',
            unique_together={('user', 'annonce')},
        ),
    ]
