# Generated by Django 6.0.2 on 2026-02-04 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_correct',
            new_name='correct',
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_data',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='points_awarded',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='student',
        ),
        migrations.AddField(
            model_name='answer',
            name='given_answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='attempt',
            name='attempt_type',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('exam', 'Exam')], default='exercise', max_length=20),
        ),
        migrations.AddField(
            model_name='attempt',
            name='max_score',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
