# Generated by Django 5.2.7 on 2025-12-11 03:27

import billing.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du plan')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('duration_days', models.PositiveIntegerField(choices=[(1, '24 heures'), (7, '7 jours'), (30, '30 jours'), (365, '1 an')], default=30, verbose_name='Durée (jours)')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix USD')),
                ('price_xaf', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix FCFA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Plan populaire')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Fonctionnalités')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['order', 'duration_days'],
            },
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(help_text='Code unique pour identifier les ventes', max_length=20, unique=True, verbose_name='Code de parrainage')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Pourcentage de commission sur chaque vente (ex: 20.00)', max_digits=5, verbose_name='Taux de commission (%)')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total gagné (USD)')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='Nombre de ventes')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('BANNED', 'Banni')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(blank=True, help_text='Ex: Mobile Money, Virement bancaire', max_length=50, verbose_name='Méthode de paiement')),
                ('payment_details', models.TextField(blank=True, help_text='Numéro de téléphone Mobile Money, RIB, etc.', verbose_name='Détails de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Affilié / Revendeur',
                'verbose_name_plural': 'Affiliés / Revendeurs',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_subscriptions', to='billing.affiliate', verbose_name='Parrainé par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(default=billing.models.default_expiration_date)),
                ('created_by_affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_codes', to='billing.affiliate', verbose_name="Créé par l'affilié")),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='billing.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Code prépayé',
                'verbose_name_plural': 'Codes prépayés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('type', models.CharField(choices=[('CREDIT', 'Crédit / Achat'), ('DEBIT', 'Débit'), ('REFUND', 'Remboursement')], default='CREDIT', max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=12)),
                ('payment_method', models.CharField(blank=True, choices=[('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Carte bancaire'), ('CODE', 'Code prépayé'), ('MANUAL', 'Manuel')], max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('external_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscriptionplan')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_transactions', to='billing.affiliate', verbose_name='Transaction via affilié')),
                ('related_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.creditcode')),
                ('related_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (USD)')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pourcentage appliqué')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('PAID', 'Payée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payée le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='billing.affiliate', verbose_name='Affilié')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='billing.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
