# Generated by Django 5.2.7 on 2025-12-11 04:32

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total gagné (USD)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant (USD)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix USD'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_xaf',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Prix FCFA'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status', 'created_at'], name='billing_com_status_58567f_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcode',
            index=models.Index(fields=['is_used', 'expiration_date'], name='billing_cre_is_used_8a4aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'is_active'], name='billing_sub_user_id_156439_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expires_at'], name='billing_sub_expires_b7e94d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_active', 'order'], name='billing_sub_is_acti_df11d2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='billing_tra_status_312567_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_transaction_id'], name='billing_tra_externa_cd4e8d_idx'),
        ),
    ]
