# Generated by Django 5.2.7 on 2026-01-23 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_affiliate_total_earned_alter_commission_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcode',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='creditcode',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_created_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditcode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='creditcode',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creditcode',
            name='used_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcode',
            name='uses_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='creditcode',
            index=models.Index(fields=['batch_id'], name='billing_cre_batch_i_71cfaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.UniqueConstraint(fields=('transaction',), name='uniq_commission_per_transaction'),
        ),
    ]
