# Generated by Django 5.2.7 on 2026-01-23 18:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_creditcode_batch_id_creditcode_created_by_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='creditcode',
            name='created_by_affiliate',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='referred_by',
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='creditcode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ('order', 'duration_days')},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='commission',
            name='billing_com_status_58567f_idx',
        ),
        migrations.RemoveIndex(
            model_name='creditcode',
            name='billing_cre_is_used_8a4aa6_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='billing_sub_user_id_156439_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='billing_sub_expires_b7e94d_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscriptionplan',
            name='billing_sub_is_acti_df11d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='billing_tra_status_312567_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='billing_tra_externa_cd4e8d_idx',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='external_transaction_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='commission',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='commission',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='commission',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='commission',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='billing.transaction'),
        ),
        migrations.AlterField(
            model_name='creditcode',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='creditcode',
            name='code',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='creditcode',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditcode',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditcode',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='creditcode',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_codes', to='billing.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_xaf',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('CODE', 'CODE'), ('CARD', 'CARD'), ('MOBILE_MONEY', 'MOBILE_MONEY'), ('WALLET_TOPUP', 'WALLET_TOPUP'), ('OTHER', 'OTHER')], default='OTHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], default='CREDIT', max_length=16),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'expires_at'], name='billing_sub_user_id_f3a2ac_idx'),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commission',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='billing.affiliateprofile'),
        ),
        migrations.AddField(
            model_name='referral',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='billing.affiliateprofile'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Affiliate',
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['created_at'], name='billing_ref_created_d71be5_idx'),
        ),
    ]
