# Generated by Django 5.2.7 on 2026-01-27 15:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_affiliateprofile_referral_remove_affiliate_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('client_full_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('service_name', models.CharField(max_length=255)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('payment_method', models.CharField(blank=True, max_length=64, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('paid', 'Payé'), ('pending', 'En attente'), ('failed', 'Échoué')], default='paid', max_length=16)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
