# Generated by Django 5.2.7 on 2026-04-12 11:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Généré automatiquement depuis le premier message', max_length=200, verbose_name='Titre (auto-généré)')),
                ('module_context', models.CharField(choices=[('global', 'Global — Tous modules'), ('resto', 'E-Shelle Resto'), ('boutique', 'E-Shelle Boutique'), ('formations', 'Formations'), ('agro', 'E-Shelle Agro'), ('gaz', 'E-Shelle Gaz'), ('pharma', 'E-Shelle Pharma'), ('pressing', 'E-Shelle Pressing'), ('rencontres', 'E-Shelle Love'), ('njangi', 'Njangi Digital'), ('immobilier', 'E-Shelle Immo'), ('marketing', 'Marketing & Croissance')], default='global', max_length=20, verbose_name='Contexte module')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'verbose_name_plural': 'Conversations IA',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_appel', models.CharField(choices=[('chat', 'Chat GPT-4o'), ('image', 'Image DALL-E 3')], max_length=10)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cout_estime_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('model_used', models.CharField(default='gpt-4o', max_length=30)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log API IA',
                'verbose_name_plural': 'Logs API IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant IA'), ('system', 'Système')], max_length=10)),
                ('content', models.TextField(verbose_name='Contenu')),
                ('message_type', models.CharField(choices=[('text', 'Texte'), ('image', 'Image générée'), ('mixed', 'Texte + Image')], default='text', max_length=10)),
                ('image_url', models.CharField(blank=True, help_text='Chemin local media/ après téléchargement', max_length=500, null=True, verbose_name='URL image (DALL-E)')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens utilisés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='e_shelle_ai.aiconversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message IA',
                'verbose_name_plural': 'Messages IA',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter — Gratuit'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=15)),
                ('messages_used', models.PositiveIntegerField(default=0)),
                ('images_used', models.PositiveIntegerField(default=0)),
                ('messages_limit', models.PositiveIntegerField(default=30, verbose_name='Limite messages/mois')),
                ('images_limit', models.PositiveIntegerField(default=0, verbose_name='Limite images/mois')),
                ('reset_date', models.DateField(default=datetime.date.today, verbose_name='Date de prochain reset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quota', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Quota IA',
                'verbose_name_plural': 'Quotas IA',
            },
        ),
        migrations.CreateModel(
            name='AIUserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=dict, help_text='ex: {"ville":"Yaoundé","secteur":"restauration","objectif":"vente"}', verbose_name='Préférences détectées')),
                ('summary', models.TextField(blank=True, help_text='Condensé auto-généré par GPT-4o après N messages', verbose_name="Résumé de l'historique utilisateur")),
                ('business_context', models.JSONField(default=dict, help_text='ex: {"produits":["ndolé","eru"],"zone":"Bastos","cible":"25-40 ans"}', verbose_name='Contexte business')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memory', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mémoire utilisateur IA',
                'verbose_name_plural': 'Mémoires utilisateurs IA',
            },
        ),
    ]
