# Generated by Django 6.0.2 on 2026-05-17 15:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tchaslucpay_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solde client',
                'verbose_name_plural': 'Soldes clients',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trid', models.CharField(db_index=True, max_length=40, unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Depot'), ('WITHDRAWAL', 'Retrait'), ('CONTRIBUTION', 'Cotisation tontine'), ('LOAN_DISBURSEMENT', 'Decaissement pret'), ('LOAN_REPAYMENT', 'Remboursement pret'), ('FEE', 'Frais'), ('REVERSAL', 'Annulation comptable')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('POSTED', 'Validee'), ('REVERSED', 'Annulee'), ('FAILED', 'Echouee')], db_index=True, default='POSTED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tchaslucpay_transactions', to=settings.AUTH_USER_MODEL)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tchaslucpay_collected_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tchaslucpay_created_transactions', to=settings.AUTH_USER_MODEL)),
                ('reversed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entries', to='tchaslucpay_transactions.transaction')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='tchaslucpay_account_4da07f_idx'), models.Index(fields=['transaction_type', 'status'], name='tchaslucpay_transac_ff9531_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='tchaslucpay_transaction_amount_positive')],
            },
        ),
    ]
