# Generated by Django 6.0.2 on 2026-03-21 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_gen', models.CharField(choices=[('cours', 'Plan de cours complet'), ('lecon', 'Contenu de leçon'), ('quiz', 'Questions de quiz'), ('description', 'Description produit/formation'), ('article', 'Article de blog'), ('email', 'Email marketing'), ('devis', 'Devis automatique'), ('faq', 'FAQ'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('modele', models.CharField(default='claude-opus-4-6', help_text='Modèle IA utilisé', max_length=100)),
                ('prompt', models.TextField(help_text='Prompt envoyé au modèle')),
                ('resultat', models.TextField(blank=True, help_text='Résultat généré')),
                ('parametres', models.JSONField(blank=True, default=dict, help_text='Paramètres (langue, niveau, ton, etc.)')),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('succes', 'Succès'), ('erreur', 'Erreur')], default='en_cours', max_length=20)),
                ('erreur', models.TextField(blank=True)),
                ('sauvegarde', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duree_ms', models.PositiveIntegerField(default=0, help_text='Durée de génération en ms')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generations_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Génération IA',
                'verbose_name_plural': 'Générations IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplatePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_gen', models.CharField(choices=[('cours', 'Plan de cours complet'), ('lecon', 'Contenu de leçon'), ('quiz', 'Questions de quiz'), ('description', 'Description produit/formation'), ('article', 'Article de blog'), ('email', 'Email marketing'), ('devis', 'Devis automatique'), ('faq', 'FAQ'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('template', models.TextField(help_text='Template de prompt avec variables {{titre}}, {{niveau}}, {{langue}}, etc.')),
                ('variables', models.JSONField(blank=True, default=list, help_text='["titre", "niveau", "langue"]')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de prompt',
                'ordering': ['type_gen', 'nom'],
            },
        ),
    ]
