# Generated by Django 5.2.7 on 2026-01-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('italian_courses', '0002_repair_missing_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='...'),
        ),
    ]
