# Generated by Django 5.2.7 on 2026-01-28 15:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('italian_courses', '0004_add_cover_image_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('question__order', 'order', 'id'), 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Course category', 'verbose_name_plural': 'Course categories'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('category__order', 'category__name', 'order', 'title'), 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ('-last_accessed_at',), 'verbose_name': 'Lesson progress', 'verbose_name_plural': 'Lesson progress'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('quiz__order', 'order', 'id'), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('lesson__order', 'order', 'title'), 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='italian_cou_is_publ_f65b79_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonprogress',
            name='italian_cou_user_id_750fa9_idx',
        ),
        migrations.RenameField(
            model_name='lessonprogress',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='lessonprogress',
            old_name='updated_at',
            new_name='last_accessed_at',
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='level',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='order_index',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order_index',
        ),
        migrations.AddField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='italian_courses/audio/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='last_position_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='progress_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pourcentage entre 0.00 et 100.00', max_digits=5),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=220),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='italian_courses.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='italian_lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='italian_courses.lesson'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='italian_cou_user_id_f78943_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'completed'], name='italian_cou_lesson__2fbfda_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uniq_lesson_slug_per_category'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_progress_per_user_lesson'),
        ),
    ]
