# Generated by Django 5.2.7 on 2026-04-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='base_fund_required',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Montant minimum que chaque membre doit maintenir (ex: 30 000 FCFA)', max_digits=12, verbose_name='Fonds de base obligatoire (FCFA)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Remboursé le'),
        ),
        migrations.AddField(
            model_name='membership',
            name='reliability_score',
            field=models.PositiveSmallIntegerField(default=100, help_text='Score 0-100 basé sur les retards, absences et remboursements', verbose_name='Score de fiabilité'),
        ),
        migrations.CreateModel(
            name='MonthlyGroupInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mois (1-12)')),
                ('total_pool', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Pool total (FCFA)')),
                ('total_loans_outstanding', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Encours prêts (FCFA)')),
                ('total_interest_generated', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Intérêts générés (FCFA)')),
                ('nb_active_loans', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de prêts actifs')),
                ('nb_depositors', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de déposants')),
                ('is_calculated', models.BooleanField(default=False, verbose_name='Calculé')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Calculé le')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_interests', to='njangi.group', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Intérêts mensuels groupe',
                'verbose_name_plural': 'Intérêts mensuels groupes',
                'ordering': ['-year', '-month'],
                'unique_together': {('group', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MemberMonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_balance', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Dépôt actif (FCFA)')),
                ('pool_share_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Part dans le pool (%)')),
                ('contribution_to_loans', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Contribution aux prêts (FCFA)')),
                ('interest_earned', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Intérêts gagnés ce mois (FCFA)')),
                ('cumulative_interest', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Intérêts cumulés (FCFA)')),
                ('wallet_balance', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Avoirs totaux (FCFA)')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statements', to='njangi.membership', verbose_name='Membre')),
                ('monthly_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_statements', to='njangi.monthlygroupinterest', verbose_name='Mois')),
            ],
            options={
                'verbose_name': 'Relevé mensuel membre',
                'verbose_name_plural': 'Relevés mensuels membres',
                'ordering': ['-monthly_record__year', '-monthly_record__month'],
                'unique_together': {('membership', 'monthly_record')},
            },
        ),
    ]
