# Generated by Django 5.2.7 on 2026-04-19 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0002_group_base_fund_required_loan_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratuit'), ('standard', 'Standard'), ('pro', 'Pro'), ('association', 'Association')], default='free', max_length=15, verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='group',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expire le'),
        ),
        migrations.AddField(
            model_name='group',
            name='plan_note',
            field=models.TextField(blank=True, verbose_name='Note activation'),
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('standard', 'Standard — 3 000 FCFA/mois'), ('pro', 'Pro — 7 000 FCFA/mois'), ('association', 'Association — 15 000 FCFA/mois')], max_length=15)),
                ('duration_months', models.PositiveSmallIntegerField(choices=[(1, '1 mois'), (3, '3 mois  (-5%)'), (6, '6 mois  (-10%)'), (12, '12 mois (-15%)')], default=1, verbose_name='Durée')),
                ('amount_expected', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Montant attendu (FCFA)')),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Montant déclaré (FCFA)')),
                ('payment_method', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('depot_banque', 'Dépôt bancaire'), ('autre', 'Autre')], max_length=20, verbose_name='Méthode de paiement')),
                ('phone_used', models.CharField(blank=True, max_length=20, verbose_name='Numéro utilisé')),
                ('payment_date', models.DateField(verbose_name='Date du paiement')),
                ('payment_ref', models.CharField(blank=True, max_length=100, verbose_name='Référence / reçu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='njangi.group')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='njangi_sub_processed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='njangi_sub_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'abonnement",
                'verbose_name_plural': "Demandes d'abonnement",
                'ordering': ['-created_at'],
            },
        ),
    ]
