# Generated by Django 5.2.7 on 2026-04-20 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njangi', '0003_group_plan_group_plan_expires_at_group_plan_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('session_created', 'Séance créée'), ('session_opened', 'Séance ouverte'), ('session_closed', 'Séance clôturée'), ('contribution_paid', 'Cotisation payée'), ('contribution_penalized', 'Cotisation pénalisée'), ('loan_requested', 'Prêt demandé'), ('loan_approved', 'Prêt approuvé'), ('loan_rejected', 'Prêt refusé'), ('loan_disbursed', 'Prêt décaissé'), ('loan_repayment', 'Remboursement enregistré'), ('loan_completed', 'Prêt remboursé intégralement'), ('loan_defaulted', 'Prêt en défaut'), ('deposit_created', 'Dépôt créé'), ('deposit_withdrawn', 'Dépôt retiré'), ('member_joined', 'Membre rejoint'), ('member_left', 'Membre parti'), ('role_changed', 'Rôle modifié'), ('plan_upgraded', 'Plan mis à niveau'), ('plan_rejected', 'Demande plan refusée'), ('fund_adjustment', 'Ajustement fond commun'), ('interest_calculated', 'Intérêts calculés'), ('other', 'Autre')], max_length=30, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='Modèle concerné')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('description', models.TextField(verbose_name='Description')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Données extra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date/heure')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='njangi.group', verbose_name='Groupe')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='njangi_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Réalisé par')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', '-created_at'], name='njangi_audi_group_i_4f758d_idx'), models.Index(fields=['action'], name='njangi_audi_action_0ed0ac_idx')],
            },
        ),
    ]
