# Generated by Django 5.2.7 on 2026-04-11 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='✨', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(verbose_name='Description du produit')),
                ('prix', models.CharField(max_length=50, verbose_name='Prix')),
                ('cible', models.CharField(max_length=200, verbose_name='Cible / audience')),
                ('pays', models.CharField(choices=[('cm', 'Cameroun'), ('ci', "Côte d'Ivoire"), ('sn', 'Sénégal'), ('cd', 'RD Congo'), ('ga', 'Gabon'), ('ng', 'Nigeria'), ('gh', 'Ghana'), ('bj', 'Bénin'), ('ml', 'Mali'), ('bf', 'Burkina Faso')], default='cm', max_length=5, verbose_name='Pays cible')),
                ('modules_selected', models.JSONField(default=list, verbose_name='Modules sélectionnés')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.JSONField(blank=True, default=list)),
                ('description_generated', models.TextField(blank=True)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('facebook_post', models.TextField(blank=True)),
                ('instagram_post', models.TextField(blank=True)),
                ('whatsapp_message', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('tiktok_script', models.TextField(blank=True)),
                ('voice_over', models.TextField(blank=True)),
                ('chatbot_reply', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='adgen.adcampaign')),
            ],
            options={
                'verbose_name': 'Contenu généré',
                'verbose_name_plural': 'Contenus générés',
            },
        ),
        migrations.CreateModel(
            name='AdUsageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaigns_count', models.IntegerField(default=0)),
                ('tokens_total', models.IntegerField(default=0)),
                ('last_generation', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adgen_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stat utilisateur',
                'verbose_name_plural': 'Stats utilisateurs',
            },
        ),
    ]
