# Generated by Django 6.0.2 on 2026-03-22 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('3eme', 'Troisième'), ('2nde', 'Seconde'), ('1ere_a', 'Première A'), ('1ere_c', 'Première C'), ('1ere_d', 'Première D'), ('tle_a', 'Terminale A'), ('tle_c', 'Terminale C'), ('tle_d', 'Terminale D')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('examen_fin_annee', models.CharField(blank=True, choices=[('bepc', 'BEPC'), ('probatoire', 'Probatoire'), ('baccalaureat', 'Baccalauréat')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#2E7D32', max_length=7)),
                ('icone', models.CharField(default='calculator', max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('numero', models.PositiveIntegerField()),
                ('categorie', models.CharField(choices=[('algebre', 'Algèbre'), ('geometrie', 'Géométrie'), ('analyse', 'Analyse'), ('statistiques', 'Statistiques & Probabilités'), ('arithmetique', 'Arithmétique'), ('trigonometrie', 'Trigonométrie'), ('logique', 'Logique & Ensembles'), ('complexes', 'Nombres Complexes'), ('suites', 'Suites & Séries'), ('matrices', 'Matrices & Déterminants')], max_length=30)),
                ('difficulte', models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile'), (4, 'Très difficile')], default=2)),
                ('description', models.TextField(blank=True)),
                ('objectifs', models.JSONField(default=list)),
                ('duree_estimee', models.PositiveIntegerField(default=60)),
                ('is_published', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequis', models.ManyToManyField(blank=True, to='math_cm.chapitre')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='math_cm.classe')),
            ],
            options={
                'ordering': ['classe', 'numero'],
                'unique_together': {('classe', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='EpreuveExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('type_examen', models.CharField(choices=[('bepc', 'BEPC'), ('probatoire', 'Probatoire'), ('baccalaureat', 'Baccalauréat'), ('entrainement', 'Entraînement')], max_length=20)),
                ('serie', models.CharField(choices=[('toutes', 'Toutes séries'), ('A', 'Série A'), ('C', 'Série C'), ('D', 'Série D')], default='toutes', max_length=10)),
                ('annee', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('duree', models.PositiveIntegerField(default=180)),
                ('bareme_total', models.PositiveIntegerField(default=20)),
                ('contenu', models.JSONField(default=dict)),
                ('correction_complete', models.JSONField(default=dict)),
                ('is_premium', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='math_cm.classe')),
            ],
            options={
                'ordering': ['-annee', 'classe'],
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('ordre', models.PositiveIntegerField()),
                ('type_lecon', models.CharField(choices=[('definition', 'Définition & Théorie'), ('methode', 'Méthode & Technique'), ('exemple', 'Exemples résolus'), ('recapitulatif', 'Récapitulatif')], default='definition', max_length=20)),
                ('contenu', models.JSONField(default=dict)),
                ('contenu_html', models.TextField(blank=True)),
                ('duree_lecture', models.PositiveIntegerField(default=15)),
                ('is_free', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='math_cm.chapitre')),
            ],
            options={
                'ordering': ['chapitre', 'ordre'],
                'unique_together': {('chapitre', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField()),
                ('type_exercice', models.CharField(choices=[('qcm', 'QCM'), ('vrai_faux', 'Vrai ou Faux'), ('calcul', 'Calcul dirigé'), ('probleme', 'Problème ouvert'), ('demonstration', 'Démonstration'), ('application', 'Application directe'), ('synthese', 'Synthèse')], max_length=20)),
                ('niveau', models.CharField(choices=[('decouverte', '⭐ Découverte'), ('entrainement', '⭐⭐ Entraînement'), ('approfondissement', '⭐⭐⭐ Approfondissement'), ('examen', '⭐⭐⭐⭐ Niveau examen')], default='entrainement', max_length=20)),
                ('enonce', models.JSONField(default=dict)),
                ('correction', models.JSONField(default=dict)),
                ('options_qcm', models.JSONField(default=list)),
                ('bareme', models.PositiveIntegerField(default=5)),
                ('duree_recommandee', models.PositiveIntegerField(default=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='math_cm.chapitre')),
                ('lecon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices', to='math_cm.lecon')),
            ],
            options={
                'ordering': ['chapitre', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ProfilEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etablissement', models.CharField(blank=True, max_length=200)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('points_total', models.PositiveIntegerField(default=0)),
                ('streak_jours', models.PositiveIntegerField(default=0)),
                ('derniere_connexion_app', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='math_cm.classe')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_eleve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('type_badge', models.CharField(choices=[('completion', 'Complétion chapitre'), ('score', 'Score parfait'), ('streak', 'Régularité'), ('rapidite', 'Rapidité'), ('examen', 'Réussite examen')], max_length=20)),
                ('icone', models.CharField(max_length=100)),
                ('condition_points', models.PositiveIntegerField(default=0)),
                ('eleves', models.ManyToManyField(blank=True, related_name='badges', to='math_cm.profileleve')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatEpreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('temps_passe', models.PositiveIntegerField()),
                ('reponses', models.JSONField(default=dict)),
                ('analyse', models.JSONField(default=dict)),
                ('date_passage', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_epreuves', to='math_cm.profileleve')),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_cm.epreuveexamen')),
            ],
            options={
                'ordering': ['-date_passage'],
            },
        ),
        migrations.CreateModel(
            name='ResultatExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentative', models.PositiveIntegerField(default=1)),
                ('score', models.FloatField(default=0)),
                ('points_obtenus', models.FloatField(default=0)),
                ('reponses_eleve', models.JSONField(default=dict)),
                ('temps_passe', models.PositiveIntegerField(default=0)),
                ('correction_consultee', models.BooleanField(default=False)),
                ('date_tentative', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='math_cm.profileleve')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_cm.exercice')),
            ],
            options={
                'ordering': ['-date_tentative'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('temps_passe', models.PositiveIntegerField(default=0)),
                ('nb_consultations', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='math_cm.profileleve')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_cm.lecon')),
            ],
            options={
                'unique_together': {('eleve', 'lecon')},
            },
        ),
    ]
