# Generated by Django 5.2.7 on 2026-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieagro',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
