# Generated by Django 6.0.2 on 2026-03-21 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=25)),
                ('sujet', models.CharField(choices=[('devis', 'Demande de devis'), ('support', 'Support technique'), ('partenariat', 'Partenariat'), ('facturation', 'Facturation'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('repondu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OffreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('icone', models.CharField(default='🌐', max_length=10)),
                ('description', models.TextField()),
                ('prix_base', models.DecimalField(blank=True, decimal_places=2, help_text='Null = sur devis', max_digits=12, null=True)),
                ('delai_jours', models.PositiveIntegerField(default=7, help_text='Délai de livraison en jours')),
                ('features', models.JSONField(blank=True, default=list, help_text='["Feature 1", "Feature 2", ...]')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Offre de service',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=25)),
                ('entreprise', models.CharField(blank=True, max_length=200)),
                ('type_projet', models.CharField(choices=[('vitrine', 'Site vitrine'), ('ecommerce', 'Site e-commerce'), ('webapp', 'Application web'), ('mobile', 'Application mobile'), ('agent_ia', 'Agent IA personnalisé'), ('autre', 'Autre')], max_length=20)),
                ('budget', models.CharField(choices=[('lt50k', '< 50 000 FCFA'), ('50_100k', '50 000 – 100 000 FCFA'), ('100_200k', '100 000 – 200 000 FCFA'), ('200_500k', '200 000 – 500 000 FCFA'), ('gt500k', '> 500 000 FCFA'), ('nd', 'À discuter')], default='nd', max_length=20)),
                ('delai_souhaite', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('config_data', models.JSONField(blank=True, default=dict, help_text='Données du wizard configurateur')),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('contacte', 'Contacté'), ('en_cours', "En cours d'analyse"), ('envoye', 'Devis envoyé'), ('accepte', 'Devis accepté'), ('refuse', 'Devis refusé'), ('termine', 'Projet terminé')], default='nouveau', max_length=20)),
                ('note_interne', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjetPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/portfolio/')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='["Django", "React", "IA", ...]')),
                ('lien_demo', models.URLField(blank=True)),
                ('lien_code', models.URLField(blank=True)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='services.categorieportfolio')),
            ],
            options={
                'verbose_name': 'Projet portfolio',
                'ordering': ['ordre', '-created_at'],
            },
        ),
    ]
