# Generated by Django 6.0.2 on 2026-03-30 21:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('subject_type', models.CharField(choices=[('math', 'Mathématiques'), ('french', 'Français'), ('physics', 'Physique-Chimie'), ('biology', 'SVT'), ('history', 'Histoire-Géo'), ('english', 'Anglais'), ('philosophy', 'Philosophie'), ('economics', 'Économie'), ('computer', 'Informatique'), ('other', 'Autre')], max_length=30, verbose_name='Type')),
                ('level', models.CharField(choices=[('bepc', 'BEPC'), ('probatoire', 'Probatoire'), ('bac', 'Baccalauréat'), ('licence', 'Licence'), ('master', 'Master')], max_length=20, verbose_name='Niveau')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name="Année d'examen")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='edu_platform/subjects/', verbose_name='Image de couverture')),
                ('is_premium', models.BooleanField(default=True, verbose_name='Contenu premium')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['level', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du forfait')),
                ('plan_type', models.CharField(choices=[('quarterly', 'Trimestriel'), ('annual', 'Annuel')], max_length=20)),
                ('price_xaf', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('duration_days', models.IntegerField(verbose_name='Durée (jours)')),
                ('features', models.JSONField(default=list, verbose_name='Fonctionnalités incluses')),
                ('is_active', models.BooleanField(default=True)),
                ('badge_label', models.CharField(blank=True, help_text='Ex: Populaire, Meilleure offre', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['price_xaf'],
            },
        ),
        migrations.CreateModel(
            name='EduProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('country', models.CharField(default='CM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edu_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Étudiant',
                'verbose_name_plural': 'Profils Étudiants',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID transaction interne')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence opérateur')),
                ('provider', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo')], max_length=30, verbose_name='Opérateur')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro Mobile Money')),
                ('amount_xaf', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('initiated', 'Initiée'), ('confirmed', 'Confirmée'), ('failed', 'Échouée'), ('refunded', 'Remboursée'), ('expired', 'Expirée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_data', models.JSONField(blank=True, null=True, verbose_name='Données webhook brutes')),
                ('webhook_received_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu_platform.subscriptionplan', verbose_name='Plan choisi')),
            ],
            options={
                'verbose_name': 'Transaction Mobile Money',
                'verbose_name_plural': 'Transactions Mobile Money',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('subject', "Sujet d'examen"), ('correction', 'Correction officielle'), ('correction_proposed', 'Correction proposée'), ('course_notes', 'Cours / Résumé')], max_length=30, verbose_name='Type de document')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('file', models.FileField(upload_to='edu_platform/documents/', verbose_name='Fichier PDF')),
                ('preview_pages', models.IntegerField(default=2, verbose_name='Pages en aperçu gratuit')),
                ('is_downloadable', models.BooleanField(default=False, verbose_name='Téléchargeable')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size_kb', models.IntegerField(default=0, verbose_name='Taille (Ko)')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='edu_platform.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': "Document d'examen",
                'verbose_name_plural': "Documents d'examen",
                'ordering': ['subject', 'doc_type', '-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='allowed_plans',
            field=models.ManyToManyField(blank=True, to='edu_platform.subscriptionplan', verbose_name='Plans autorisés'),
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name="Code d'accès")),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unused', 'Non utilisé'), ('active', 'Actif'), ('expired', 'Expiré'), ('revoked', 'Révoqué')], default='unused', max_length=20)),
                ('activation_count', models.IntegerField(default=0)),
                ('max_activations', models.IntegerField(default=1)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edu_access_codes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_code', to='edu_platform.paymenttransaction')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_codes', to='edu_platform.subscriptionplan')),
            ],
            options={
                'verbose_name': "Code d'accès",
                'verbose_name_plural': "Codes d'accès",
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video_url', models.URLField(blank=True, verbose_name='URL YouTube/Vimeo (gratuit)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='edu_platform/videos/', verbose_name='Fichier vidéo (premium)')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Durée (minutes)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='edu_platform/video_thumbnails/', verbose_name='Miniature')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Extrait gratuit')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='edu_platform.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Leçon vidéo',
                'verbose_name_plural': 'Leçons vidéo',
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DeviceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(max_length=128, verbose_name='Empreinte appareil (SHA256)')),
                ('device_label', models.CharField(blank=True, max_length=100, verbose_name='Libellé appareil')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Première connexion')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Dernière connexion')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Appareil principal')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('connection_count', models.IntegerField(default=1, verbose_name='Nombre de connexions')),
                ('access_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_bindings', to='edu_platform.accesscode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appareil enregistré',
                'verbose_name_plural': 'Appareils enregistrés',
                'ordering': ['-last_seen'],
                'unique_together': {('access_code', 'device_fingerprint')},
            },
        ),
    ]
