# Generated by Django 6.0.2 on 2026-04-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_platform', '0002_section_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examdocument',
            options={'ordering': ['subject', 'doc_type', '-uploaded_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['section', 'level', 'order', 'title'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année (ex: 2024)'),
        ),
    ]
