# Generated by Django 6.0.2 on 2026-03-21 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrePlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(default='E-Shelle', max_length=200)),
                ('slogan', models.CharField(default="L'expérience à votre service", max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('couleur_primaire', models.CharField(default='#2E7D32', max_length=10)),
                ('couleur_accent', models.CharField(default='#F57C00', max_length=10)),
                ('email_contact', models.EmailField(default='contact@e-shelle.com', max_length=254)),
                ('telephone', models.CharField(default='+237 000 000 000', max_length=25)),
                ('whatsapp', models.CharField(default='+237000000000', max_length=25)),
                ('adresse', models.TextField(blank=True)),
                ('lien_facebook', models.URLField(blank=True)),
                ('lien_linkedin', models.URLField(blank=True)),
                ('lien_youtube', models.URLField(blank=True)),
                ('lien_whatsapp', models.URLField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('mtn_api_key', models.CharField(blank=True, max_length=200)),
                ('airtel_api_key', models.CharField(blank=True, max_length=200)),
                ('module_formations', models.BooleanField(default=True)),
                ('module_boutique', models.BooleanField(default=True)),
                ('module_services', models.BooleanField(default=True)),
                ('module_ai', models.BooleanField(default=True)),
                ('maintenance', models.BooleanField(default=False)),
                ('message_maintenance', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre plateforme',
                'verbose_name_plural': 'Paramètres plateforme',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('achat', 'Nouvel achat'), ('inscription', 'Nouvelle inscription'), ('message', 'Message reçu'), ('badge', 'Badge obtenu'), ('devis', 'Nouveau devis'), ('paiement', 'Paiement reçu'), ('systeme', 'Notification système')], default='systeme', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('url_action', models.CharField(blank=True, max_length=500)),
                ('lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
