# Generated by Django 6.0.2 on 2026-03-21 16:17

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('TEACHER', 'Enseignant / Formateur'), ('PARENT', 'Parent'), ('STUDENT', 'Élève / Apprenant'), ('CLIENT', 'Client / Entrepreneur'), ('VENDOR', 'Vendeur / Partenaire')], default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_upload_path)),
                ('bio', models.TextField(blank=True, default='')),
                ('telephone', models.CharField(blank=True, default='', max_length=25)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('pays', models.CharField(blank=True, default='Cameroun', max_length=100)),
                ('site_web', models.URLField(blank=True, default='')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plan', models.CharField(choices=[('free', 'Gratuit'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('plan_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
