# Generated by Django 5.2.7 on 2026-04-11 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(choices=[('adgen', 'AdGen — Publicités IA'), ('resto', 'E-Shelle Resto'), ('rencontres', 'E-Shelle Love'), ('njangi', 'Njangi Digital'), ('edu', 'EduCam Pro'), ('formations', 'Formations'), ('boutique', 'Boutique'), ('agro', 'E-Shelle Agro')], db_index=True, max_length=30)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('free', 'Gratuit'), ('trial', 'Essai'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price_xaf', models.PositiveIntegerField(default=0)),
                ('price_eur', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('features', models.JSONField(default=list)),
                ('is_free', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Plan d'application",
                'verbose_name_plural': "Plans d'application",
                'ordering': ['app_key', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AppSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Essai gratuit'), ('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé'), ('pending', 'En attente')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=200)),
                ('auto_renew', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.appplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_xaf', models.PositiveIntegerField(default=0)),
                ('method', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('stripe', 'Carte bancaire'), ('cinetpay', 'CinetPay'), ('manual', 'Manuel (admin)'), ('free', 'Gratuit')], default='manual', max_length=30)),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échec'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.appsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Historique paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
