# Generated by Django 5.2.7 on 2026-04-11 16:24

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appplan_appsubscription_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=accounts.models._generate_code, max_length=20, unique=True)),
                ('label', models.CharField(help_text='Ex: Pack AdGen Pro 30j — Jean Dupont', max_length=150)),
                ('apps', models.JSONField(default=list, help_text='Liste des app_key accessibles. Ex: ["adgen", "njangi"] ou ["all"] pour tout.')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text="Durée d'accès en jours")),
                ('price_xaf', models.PositiveIntegerField(default=0, help_text='Montant reçu en FCFA')),
                ('payment_method', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('wave', 'Wave'), ('cash', 'Espèces'), ('offert', 'Offert / Test')], default='orange_money', max_length=20)),
                ('payment_ref', models.CharField(blank=True, default='', help_text='Référence paiement MoMo/Wave', max_length=200)),
                ('client_name', models.CharField(blank=True, default='', help_text='Nom du client pour référence', max_length=150)),
                ('client_phone', models.CharField(blank=True, default='', help_text='Téléphone du client', max_length=25)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes internes (non visibles du client)')),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver pour invalider le code')),
                ('is_used', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Calculé automatiquement à l'activation", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_codes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Code d'accès",
                'verbose_name_plural': "Codes d'accès",
                'ordering': ['-created_at'],
            },
        ),
    ]
