# Generated by Django 5.2.7 on 2026-04-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_globalaccesscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appplan',
            name='app_key',
            field=models.CharField(choices=[('adgen', 'AdGen — Publicités IA'), ('resto', 'E-Shelle Resto'), ('rencontres', 'E-Shelle Love'), ('njangi', 'Njangi Digital'), ('edu', 'EduCam Pro'), ('formations', 'Formations'), ('boutique', 'Boutique'), ('agro', 'E-Shelle Agro'), ('gaz', 'E-Shelle Gaz')], db_index=True, max_length=30),
        ),
    ]
