# Generated by Django 6.0.2 on 2026-03-24 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSoumissionVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('type_transaction', models.CharField(choices=[('VENTE', 'Vente'), ('LOCATION', 'Location')], default='VENTE', max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('prix', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('RECU', 'Reçu'), ('EN_TRAITEMENT', 'En traitement'), ('PUBLIE', 'Publié'), ('REJETE', 'Rejeté')], default='RECU', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Soumission véhicule',
                'verbose_name_plural': 'Soumissions véhicules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PARTICULIER', 'Particulier'), ('CONCESSIONNAIRE', 'Concessionnaire'), ('GARAGE', 'Garage / Mécanicien'), ('LOUEUR', 'Loueur professionnel')], default='PARTICULIER', max_length=20)),
                ('compte_type', models.CharField(choices=[('FREE', 'Gratuit (3 annonces)'), ('PREMIUM', 'Premium (illimité)')], default='FREE', max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='auto/profils/')),
                ('description', models.TextField(blank=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('date_expiration_premium', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_auto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Auto',
                'verbose_name_plural': 'Profils Auto',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('type_transaction', models.CharField(choices=[('VENTE', 'Vente'), ('LOCATION', 'Location')], default='VENTE', max_length=10)),
                ('type_carrosserie', models.CharField(choices=[('BERLINE', 'Berline'), ('SUV', 'SUV / 4x4'), ('PICKUP', 'Pick-up'), ('MINIBUS', 'Minibus'), ('CAMION', 'Camion'), ('MOTO', 'Moto'), ('BUS', 'Bus'), ('UTILITAIRE', 'Utilitaire'), ('COUPE', 'Coupé'), ('CABRIOLET', 'Cabriolet'), ('BREAK', 'Break'), ('AUTRE', 'Autre')], default='BERLINE', max_length=20)),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('EXCELLENT', 'Excellent état'), ('TRES_BON', 'Très bon état'), ('BON', 'Bon état'), ('PASSABLE', 'État passable'), ('POUR_PIECES', 'Pour pièces')], default='BON', max_length=20)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Version / Finition')),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('immatriculation', models.CharField(blank=True, max_length=30, verbose_name='Immatriculation (optionnel)')),
                ('carburant', models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('HYBRIDE', 'Hybride'), ('ELECTRIQUE', 'Électrique'), ('GPL', 'GPL'), ('AUTRE', 'Autre')], default='ESSENCE', max_length=15)),
                ('boite', models.CharField(choices=[('MANUELLE', 'Manuelle'), ('AUTOMATIQUE', 'Automatique'), ('SEMI_AUTO', 'Semi-automatique')], default='MANUELLE', max_length=15)),
                ('puissance_cv', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puissance (CV)')),
                ('cylindree', models.CharField(blank=True, max_length=20, verbose_name='Cylindrée')),
                ('conduite', models.CharField(choices=[('GAUCHE', 'Volant à gauche'), ('DROITE', 'Volant à droite')], default='GAUCHE', max_length=10)),
                ('kilometrage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage')),
                ('nombre_places', models.PositiveSmallIntegerField(default=5, verbose_name='Nombre de places')),
                ('nombre_portes', models.PositiveSmallIntegerField(default=4, verbose_name='Nombre de portes')),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('adresse_complete', models.CharField(blank=True, max_length=255)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=14)),
                ('devise', models.CharField(choices=[('XAF', 'XAF (FCFA)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)')], default='XAF', max_length=5)),
                ('periode_prix', models.CharField(choices=[('PAR_JOUR', 'Par jour'), ('PAR_MOIS', 'Par mois'), ('GLOBAL', 'Prix global')], default='GLOBAL', max_length=15)),
                ('prix_negociable', models.BooleanField(default=True, verbose_name='Prix négociable')),
                ('description', models.TextField()),
                ('options_equipements', models.TextField(blank=True, verbose_name='Options & équipements (liste libre)')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('PUBLIE', 'Publié'), ('RESERVE', 'Réservé'), ('VENDU_LOUE', 'Vendu / Loué'), ('REFUSE', 'Refusé'), ('ARCHIVE', 'Archivé')], default='EN_ATTENTE_VALIDATION', max_length=25)),
                ('est_mis_en_avant', models.BooleanField(default=False, verbose_name='Premium / En avant')),
                ('est_coup_de_coeur', models.BooleanField(default=False, verbose_name='Coup de cœur')),
                ('publie_par_admin', models.BooleanField(default=False)),
                ('note_admin', models.TextField(blank=True, verbose_name='Note interne admin')),
                ('est_dedouane', models.BooleanField(default=True, verbose_name='Dédouané')),
                ('garantie', models.CharField(blank=True, max_length=100, verbose_name='Garantie')),
                ('premiere_main', models.BooleanField(default=False, verbose_name='1ère main')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('date_disponibilite', models.DateField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-est_mis_en_avant', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalementVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('ARNAQUE', 'Arnaque / Fraude'), ('DOUBLON', 'Annonce dupliquée'), ('PRIX_ABUSIF', 'Prix abusif'), ('MAUVAISE_CAT', 'Mauvaise catégorie'), ('PHOTOS_FAUSSES', 'Photos incorrectes / volées'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('traite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='auto_cameroun.vehicule')),
            ],
            options={
                'verbose_name': 'Signalement véhicule',
                'verbose_name_plural': 'Signalements véhicules',
            },
        ),
        migrations.CreateModel(
            name='PhotoVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auto/photos/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('est_photo_principale', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='auto_cameroun.vehicule')),
            ],
            options={
                'verbose_name': 'Photo véhicule',
                'verbose_name_plural': 'Photos véhicule',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DemandeEssai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_souhaitee', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('EFFECTUE', 'Effectué')], default='EN_ATTENTE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_essai', to='auto_cameroun.vehicule')),
            ],
            options={
                'verbose_name': "Demande d'essai",
                'verbose_name_plural': "Demandes d'essai",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavorisVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_auto', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='auto_cameroun.vehicule')),
            ],
            options={
                'verbose_name': 'Favori véhicule',
                'verbose_name_plural': 'Favoris véhicules',
                'unique_together': {('user', 'vehicule')},
            },
        ),
    ]
