# Generated by Django 5.2.7 on 2026-04-12 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePressing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icone', models.CharField(default='👔', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories de pressing',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='QuartierPressing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='VillePressing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('region', models.CharField(default='Centre', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Pressing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pressing/photos/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pressing/logos/')),
                ('adresse', models.CharField(blank=True, max_length=250)),
                ('zone_livraison', models.TextField(blank=True, help_text='Quartiers couverts par la collecte/livraison')),
                ('telephone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='Sans +, ex: 237680625082', max_length=20)),
                ('whatsapp_msg', models.CharField(blank=True, max_length=300)),
                ('horaires', models.CharField(default='Lun-Sam 8h-19h', max_length=200)),
                ('collecte_domicile', models.BooleanField(default=False, help_text='Collecte des vêtements à domicile')),
                ('livraison_domicile', models.BooleanField(default=False, help_text='Livraison des vêtements traités à domicile')),
                ('delai_traitement', models.CharField(default='24-48h', help_text='Délai de traitement habituel', max_length=60)),
                ('delai_livraison', models.CharField(blank=True, help_text='Délai de livraison à domicile', max_length=60)),
                ('express', models.BooleanField(default=False, help_text='Service express disponible (même jour)')),
                ('plan_actif', models.CharField(blank=True, choices=[('basic', 'Basic — 2 000 FCFA/mois'), ('pro', 'Pro — 5 000 FCFA/mois'), ('premium', 'Premium — 10 000 FCFA/mois')], max_length=10, null=True)),
                ('abonnement_actif', models.BooleanField(default=False)),
                ('abonnement_expire_le', models.DateField(blank=True, null=True)),
                ('montant_paye', models.PositiveIntegerField(blank=True, null=True)),
                ('ref_paiement', models.CharField(blank=True, max_length=100)),
                ('notes_admin', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Visible après confirmation du paiement')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('nb_avis', models.PositiveIntegerField(default=0)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='pressings', to='pressing.categoriepressing')),
                ('gerant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressings', to=settings.AUTH_USER_MODEL)),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressings', to='pressing.quartierpressing')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pressings', to='pressing.villepressing')),
            ],
            options={
                'verbose_name': 'Pressing',
                'verbose_name_plural': 'Pressings',
                'ordering': ['-is_featured', '-is_verified', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CommandePressing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(blank=True, max_length=100)),
                ('tel_client', models.CharField(blank=True, max_length=20)),
                ('adresse_collecte', models.CharField(blank=True, help_text='Adresse pour la collecte/livraison à domicile', max_length=300)),
                ('mode', models.CharField(choices=[('depot', 'Je dépose au pressing'), ('collecte', 'Collecte à domicile')], default='depot', max_length=10)),
                ('articles', models.JSONField(default=list, help_text='Liste des articles : [{service_id, nom, qte, prix_unit}]')),
                ('notes', models.TextField(blank=True, help_text='Instructions spéciales')),
                ('montant_total', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de confirmation'), ('confirme', 'Confirmée'), ('en_cours', 'En cours de traitement'), ('pret', 'Prêt — à récupérer / à livrer'), ('livre', 'Livré / Récupéré'), ('annule', 'Annulée')], default='en_attente', max_length=15)),
                ('date_collecte', models.DateField(blank=True, help_text='Date souhaitée pour la collecte ou le dépôt', null=True)),
                ('date_pret', models.DateField(blank=True, help_text='Date estimée de fin de traitement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_pressing', to=settings.AUTH_USER_MODEL)),
                ('pressing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='pressing.pressing')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePressing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Chemise homme, Costume 2 pièces', max_length=150)),
                ('icone', models.CharField(default='👔', max_length=10)),
                ('prix', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('unite', models.CharField(choices=[('piece', 'À la pièce'), ('kg', 'Au kilogramme'), ('lot', 'Au lot'), ('forfait', 'Forfait')], default='piece', max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='pressing.categoriepressing')),
                ('pressing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pressing.pressing')),
            ],
            options={
                'verbose_name': 'Service / Tarif',
                'verbose_name_plural': 'Services & Tarifs',
                'ordering': ['categorie', 'ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='quartierpressing',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='pressing.villepressing'),
        ),
        migrations.CreateModel(
            name='AvisPressing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_pressing', to=settings.AUTH_USER_MODEL)),
                ('pressing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='pressing.pressing')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('pressing', 'auteur')},
            },
        ),
    ]
