# Generated by Django 5.2.7 on 2025-11-22 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('GENERAL', 'Général anglais'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('TOEIC', 'TOEIC')], default='GENERAL', max_length=20)),
                ('level', models.CharField(choices=[('A1', 'A1 Débutant'), ('A2', 'A2 Élémentaire'), ('B1', 'B1 Intermédiaire'), ('B2', 'B2 Intermédiaire avancé'), ('C1', 'C1 Avancé'), ('C2', 'C2 Maîtrise')], default='B1', max_length=2)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='EnglishQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('READING', 'Reading'), ('LISTENING', 'Listening'), ('USE_OF_ENGLISH', 'Grammaire/Vocabulaire')], default='READING', max_length=20)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(blank=True, max_length=255)),
                ('option_d', models.CharField(blank=True, max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='EnglishPrepApp.englishtest')),
            ],
        ),
        migrations.CreateModel(
            name='UserTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='EnglishPrepApp.englishtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnglishPrepApp.englishquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='EnglishPrepApp.usertestsession')),
            ],
        ),
    ]
