# Generated by Django 5.2.7 on 2025-11-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishPrepApp', '0002_englishuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishuserprofile',
            name='badges',
            field=models.JSONField(default=list),
        ),
    ]
