# Generated by Django 5.2.7 on 2025-11-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishPrepApp', '0003_englishuserprofile_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishquestion',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='englishtest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertestsession',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertestsession',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='englishquestion',
            name='skill',
            field=models.CharField(choices=[('READING', 'Reading'), ('LISTENING', 'Listening'), ('USE_OF_ENGLISH', 'Grammar / Vocabulary')], default='READING', max_length=20),
        ),
    ]
