# Generated by Django 5.2.7 on 2025-11-23 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishPrepApp', '0004_englishquestion_audio_url_englishtest_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('skill', models.CharField(choices=[('LISTENING', 'CO – Compréhension orale (Listening)'), ('READING', 'CE – Compréhension écrite (Reading)'), ('WRITING', 'EE – Expression écrite (Writing)'), ('SPEAKING', 'EO – Expression orale (Speaking)'), ('USE_OF_ENGLISH', 'Grammaire / Vocabulaire')], help_text='CO / CE / EO / EE / Grammaire.', max_length=32)),
                ('goal', models.CharField(blank=True, help_text='Ex : Immigration Canada, Études, Travail.', max_length=120)),
                ('level', models.CharField(blank=True, help_text='Ex : B1, B2, C1… (optionnel).', max_length=50)),
                ('short_description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Texte de cours, plan de leçon, lien vers PDF, etc.')),
                ('video_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='EnglishPrepApp.englishtest')),
            ],
            options={
                'ordering': ['skill', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EnglishExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('EASY', 'Facile'), ('MEDIUM', 'Intermédiaire'), ('HARD', 'Avancé')], default='MEDIUM', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Consignes, texte de l’exercice, etc.')),
                ('external_url', models.URLField(blank=True, help_text='Lien vers vidéo, doc, Google Drive, etc. (optionnel).')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='EnglishPrepApp.englishlesson')),
            ],
            options={
                'ordering': ['lesson', 'order', 'title'],
            },
        ),
    ]
