# Generated by Django 5.2.7 on 2025-12-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishPrepApp', '0005_englishlesson_englishexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestsession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
