# Generated by Django 6.0.2 on 2026-03-24 01:48

import django.db.models.deletion
import immobilier_cameroun.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSoumissionBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('type_bien', models.CharField(choices=[('APPARTEMENT_MEUBLE', 'Appartement meublé'), ('APPARTEMENT_NON_MEUBLE', 'Appartement non meublé'), ('STUDIO', 'Studio'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex'), ('BUREAU', 'Bureau'), ('BOUTIQUE', 'Boutique / Commerce'), ('TERRAIN', 'Terrain'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Type de bien')),
                ('ville', models.CharField(choices=[('Yaoundé', 'Yaoundé'), ('Douala', 'Douala'), ('Bafoussam', 'Bafoussam'), ('Bamenda', 'Bamenda'), ('Garoua', 'Garoua'), ('Maroua', 'Maroua'), ('Ngaoundéré', 'Ngaoundéré'), ('Bertoua', 'Bertoua'), ('Ebolowa', 'Ebolowa'), ('Kribi', 'Kribi'), ('Limbé', 'Limbé'), ('Kumba', 'Kumba'), ('Nkongsamba', 'Nkongsamba'), ('Edéa', 'Edéa'), ('Autre', 'Autre')], max_length=100, verbose_name='Ville')),
                ('quartier', models.CharField(max_length=150, verbose_name='Quartier')),
                ('description_rapide', models.TextField(verbose_name='Description rapide')),
                ('photos_jointes', models.FileField(blank=True, null=True, upload_to=immobilier_cameroun.models.soumission_upload, verbose_name='Photos jointes')),
                ('message_complementaire', models.TextField(blank=True, verbose_name='Message complémentaire')),
                ('statut', models.CharField(choices=[('RECU', 'Reçu'), ('EN_TRAITEMENT', 'En traitement'), ('PUBLIE', 'Publié'), ('REJETE', 'Rejeté')], default='RECU', max_length=15, verbose_name='Statut')),
                ('note_admin', models.TextField(blank=True, verbose_name='Note admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Soumission de bien',
                'verbose_name_plural': 'Soumissions de biens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=230, unique=True, verbose_name='Slug')),
                ('type_bien', models.CharField(choices=[('APPARTEMENT_MEUBLE', 'Appartement meublé'), ('APPARTEMENT_NON_MEUBLE', 'Appartement non meublé'), ('STUDIO', 'Studio'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex'), ('BUREAU', 'Bureau'), ('BOUTIQUE', 'Boutique / Commerce'), ('TERRAIN', 'Terrain'), ('AUTRE', 'Autre')], default='APPARTEMENT_MEUBLE', max_length=30, verbose_name='Type de bien')),
                ('type_transaction', models.CharField(choices=[('LOCATION', 'Location'), ('VENTE', 'Vente'), ('COLOCATION', 'Colocation')], default='LOCATION', max_length=20, verbose_name='Transaction')),
                ('description', models.TextField(verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Prix')),
                ('devise', models.CharField(choices=[('XAF', 'Franc CFA (XAF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dollar (USD)')], default='XAF', max_length=3, verbose_name='Devise')),
                ('periode_prix', models.CharField(choices=[('PAR_MOIS', 'Par mois'), ('PAR_JOUR', 'Par jour'), ('PRIX_FIXE', 'Prix fixe')], default='PAR_MOIS', max_length=15, verbose_name='Période')),
                ('surface', models.FloatField(blank=True, null=True, verbose_name='Surface (m²)')),
                ('nombre_pieces', models.PositiveIntegerField(default=1, verbose_name='Pièces')),
                ('nombre_chambres', models.PositiveIntegerField(default=1, verbose_name='Chambres')),
                ('nombre_salles_bain', models.PositiveIntegerField(default=1, verbose_name='Salles de bain')),
                ('etage', models.IntegerField(blank=True, null=True, verbose_name='Étage')),
                ('nombre_etages_immeuble', models.IntegerField(blank=True, null=True, verbose_name='Nb étages immeuble')),
                ('ville', models.CharField(choices=[('Yaoundé', 'Yaoundé'), ('Douala', 'Douala'), ('Bafoussam', 'Bafoussam'), ('Bamenda', 'Bamenda'), ('Garoua', 'Garoua'), ('Maroua', 'Maroua'), ('Ngaoundéré', 'Ngaoundéré'), ('Bertoua', 'Bertoua'), ('Ebolowa', 'Ebolowa'), ('Kribi', 'Kribi'), ('Limbé', 'Limbé'), ('Kumba', 'Kumba'), ('Nkongsamba', 'Nkongsamba'), ('Edéa', 'Edéa'), ('Autre', 'Autre')], max_length=100, verbose_name='Ville')),
                ('quartier', models.CharField(max_length=150, verbose_name='Quartier')),
                ('adresse_complete', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('PUBLIE', 'Publié'), ('RESERVE', 'Réservé'), ('LOUE_VENDU', 'Loué / Vendu'), ('REFUSE', 'Refusé'), ('ARCHIVE', 'Archivé')], db_index=True, default='BROUILLON', max_length=25, verbose_name='Statut')),
                ('est_mis_en_avant', models.BooleanField(db_index=True, default=False, verbose_name='Mis en avant')),
                ('est_coup_de_coeur', models.BooleanField(default=False, verbose_name='Coup de cœur')),
                ('date_disponibilite', models.DateField(blank=True, null=True, verbose_name='Disponible le')),
                ('publie_par_admin', models.BooleanField(default=False, verbose_name='Publié par admin')),
                ('note_admin', models.TextField(blank=True, verbose_name='Note admin (interne)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='Meta keywords')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens_immo', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Bien immobilier',
                'verbose_name_plural': 'Biens immobiliers',
                'ordering': ['-est_mis_en_avant', '-est_coup_de_coeur', '-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='DemandeVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('date_souhaitee', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_visite', to='immobilier_cameroun.bien')),
            ],
            options={
                'verbose_name': 'Demande de visite',
                'verbose_name_plural': 'Demandes de visite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipementBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('WIFI', 'Wi-Fi'), ('CLIMATISATION', 'Climatisation'), ('PARKING', 'Parking'), ('GARDIEN', 'Gardien'), ('GROUPE_ELECTROGENE', 'Groupe électrogène'), ('PISCINE', 'Piscine'), ('SALLE_SPORT', 'Salle de sport'), ('ASCENSEUR', 'Ascenseur'), ('BALCON', 'Balcon'), ('TERRASSE', 'Terrasse'), ('CUISINE_EQUIPEE', 'Cuisine équipée'), ('LAVE_LINGE', 'Lave-linge'), ('TV_CABLE', 'TV câble'), ('EAU_COURANTE', 'Eau courante'), ('GENERATEUR', 'Générateur'), ('CITERNE_EAU', "Citerne d'eau"), ('CLIM_DANS_CHAMBRES', 'Clim dans les chambres'), ('MEUBLE_COMPLET', 'Meublé complet')], max_length=30, verbose_name='Équipement')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='immobilier_cameroun.bien')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
        migrations.CreateModel(
            name='FavorisBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='immobilier_cameroun.bien')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_immo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
            },
        ),
        migrations.CreateModel(
            name='PhotoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=immobilier_cameroun.models.photo_bien_upload, verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('est_photo_principale', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='immobilier_cameroun.bien')),
            ],
            options={
                'verbose_name': 'Photo du bien',
                'verbose_name_plural': 'Photos du bien',
                'ordering': ['ordre', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilImmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROPRIETAIRE', 'Propriétaire'), ('AGENT', 'Agent immobilier'), ('PROMOTEUR', 'Promoteur'), ('ADMIN', 'Administrateur')], default='PROPRIETAIRE', max_length=20)),
                ('compte_type', models.CharField(choices=[('GRATUIT', 'Gratuit'), ('PREMIUM', 'Premium')], default='GRATUIT', max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('ville', models.CharField(blank=True, choices=[('Yaoundé', 'Yaoundé'), ('Douala', 'Douala'), ('Bafoussam', 'Bafoussam'), ('Bamenda', 'Bamenda'), ('Garoua', 'Garoua'), ('Maroua', 'Maroua'), ('Ngaoundéré', 'Ngaoundéré'), ('Bertoua', 'Bertoua'), ('Ebolowa', 'Ebolowa'), ('Kribi', 'Kribi'), ('Limbé', 'Limbé'), ('Kumba', 'Kumba'), ('Nkongsamba', 'Nkongsamba'), ('Edéa', 'Edéa'), ('Autre', 'Autre')], max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to=immobilier_cameroun.models.photo_profil_upload)),
                ('bio', models.TextField(blank=True)),
                ('date_expiration_premium', models.DateField(blank=True, null=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_immo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil immobilier',
                'verbose_name_plural': 'Profils immobiliers',
            },
        ),
        migrations.CreateModel(
            name='SignalementBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('FAUX_ANNONCE', 'Fausse annonce'), ('PRIX_INCORRECT', 'Prix incorrect'), ('PHOTOS_INCORRECTES', 'Photos incorrectes'), ('BIEN_INEXISTANT', 'Bien inexistant'), ('AUTRE', 'Autre')], max_length=25, verbose_name='Motif')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='immobilier_cameroun.bien')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_immo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['statut', 'ville'], name='immobilier__statut_aa9946_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['type_bien', 'type_transaction'], name='immobilier__type_bi_04f592_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipementbien',
            unique_together={('bien', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='favorisbien',
            unique_together={('user', 'bien')},
        ),
    ]
