# Generated by Django 5.2.7 on 2026-04-17 10:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='Section')),
                ('action', models.CharField(choices=[('generate_content', 'Génération de contenu'), ('publish_post', 'Publication de post'), ('schedule_post', 'Planification de post'), ('refresh_token', 'Rafraîchissement du token'), ('sync_stats', 'Synchronisation des stats'), ('agent_run', "Exécution de l'agent"), ('token_check', 'Vérification du token')], max_length=50, verbose_name='Action')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=10)),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails JSON')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (ms)')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens IA utilisés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log Agent',
                'verbose_name_plural': 'Logs Agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('total_posts_generated', models.PositiveIntegerField(default=0, verbose_name='Posts générés')),
                ('total_posts_published', models.PositiveIntegerField(default=0, verbose_name='Posts publiés')),
                ('total_posts_failed', models.PositiveIntegerField(default=0, verbose_name='Posts échoués')),
                ('total_tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens IA utilisés')),
                ('posts_by_section', models.JSONField(blank=True, default=dict, verbose_name='Posts par section')),
                ('total_reach', models.PositiveIntegerField(default=0, verbose_name='Portée totale')),
                ('total_likes', models.PositiveIntegerField(default=0, verbose_name='Likes totaux')),
                ('total_comments', models.PositiveIntegerField(default=0, verbose_name='Commentaires totaux')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistiques Agent',
                'verbose_name_plural': 'Statistiques Agents',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('annonces', 'Annonces Générales'), ('immobilier', 'Immobilier'), ('auto', 'Automobiles'), ('agro', 'Agriculture'), ('rencontres', 'Rencontres E-Shelle Love'), ('njangi', 'Njangi / Tontine'), ('edu', 'Éducation'), ('promo', 'Promotions & Offres'), ('general', 'Contenu Général'), ('resto', 'Restaurants'), ('services', 'Services')], max_length=50, unique=True, verbose_name='Section')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('tone', models.CharField(choices=[('professionnel', 'Professionnel'), ('amical', 'Amical & Chaleureux'), ('romantique', 'Romantique'), ('informatif', 'Informatif'), ('dynamique', 'Dynamique & Energique'), ('inspirant', 'Inspirant')], default='amical', max_length=30, verbose_name='Ton')),
                ('post_frequency_per_day', models.PositiveSmallIntegerField(default=1, verbose_name='Posts par jour')),
                ('preferred_hours', models.CharField(default='08:00,12:00,18:00', help_text='Heures de publication séparées par virgule (ex: 08:00,12:00)', max_length=100, verbose_name='Heures préférées')),
                ('custom_instructions', models.TextField(blank=True, help_text="Instructions spéciales pour l'agent IA", verbose_name='Instructions personnalisées')),
                ('include_emoji', models.BooleanField(default=True, verbose_name='Inclure des emojis')),
                ('include_hashtags', models.BooleanField(default=True, verbose_name='Inclure des hashtags')),
                ('max_post_length', models.PositiveIntegerField(default=500, verbose_name='Longueur max du post (caractères)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Règle de Contenu',
                'verbose_name_plural': 'Règles de Contenu',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='FacebookPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100, unique=True, verbose_name='Page ID')),
                ('page_name', models.CharField(max_length=255, verbose_name='Nom de la page')),
                ('page_access_token', models.TextField(verbose_name="Token d'accès page")),
                ('app_id', models.CharField(blank=True, max_length=100, verbose_name='App ID Meta')),
                ('app_secret', models.CharField(blank=True, max_length=255, verbose_name='App Secret Meta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration du token')),
                ('last_token_refresh', models.DateTimeField(blank=True, null=True, verbose_name='Dernier refresh token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Page Facebook',
                'verbose_name_plural': 'Configurations Pages Facebook',
            },
        ),
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('section', models.CharField(choices=[('annonces', 'Annonces Générales'), ('immobilier', 'Immobilier'), ('auto', 'Automobiles'), ('agro', 'Agriculture'), ('rencontres', 'Rencontres E-Shelle Love'), ('njangi', 'Njangi / Tontine'), ('edu', 'Éducation'), ('promo', 'Promotions & Offres'), ('general', 'Contenu Général'), ('resto', 'Restaurants'), ('services', 'Services')], max_length=50, verbose_name='Section')),
                ('template_type', models.CharField(choices=[('texte', 'Texte simple'), ('lien', 'Lien avec aperçu'), ('photo', 'Photo + texte'), ('carousel', 'Carrousel')], default='texte', max_length=20)),
                ('template_body', models.TextField(help_text='Utilisez {variable} pour les variables dynamiques', verbose_name='Corps du template')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de Post',
                'verbose_name_plural': 'Templates de Posts',
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('annonces', 'Annonces Générales'), ('immobilier', 'Immobilier'), ('auto', 'Automobiles'), ('agro', 'Agriculture'), ('rencontres', 'Rencontres E-Shelle Love'), ('njangi', 'Njangi / Tontine'), ('edu', 'Éducation'), ('promo', 'Promotions & Offres'), ('general', 'Contenu Général'), ('resto', 'Restaurants'), ('services', 'Services')], max_length=50, verbose_name='Section')),
                ('title', models.CharField(max_length=255, verbose_name='Titre interne')),
                ('content', models.TextField(verbose_name='Contenu du post')),
                ('image_url', models.URLField(blank=True, verbose_name="URL de l'image")),
                ('link_url', models.URLField(blank=True, verbose_name='URL du lien')),
                ('scheduled_at', models.DateTimeField(verbose_name='Heure de publication planifiée')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('publie', 'Publié'), ('echec', 'Échec'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requiert une approbation')),
                ('ai_generated', models.BooleanField(default=True, verbose_name='Généré par IA')),
                ('source_object_id', models.CharField(blank=True, max_length=50, verbose_name="ID de l'objet source")),
                ('source_object_type', models.CharField(blank=True, max_length=50, verbose_name="Type de l'objet source")),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='facebook_agent.facebookpageconfig')),
            ],
            options={
                'verbose_name': 'Post Planifié',
                'verbose_name_plural': 'Posts Planifiés',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('annonces', 'Annonces Générales'), ('immobilier', 'Immobilier'), ('auto', 'Automobiles'), ('agro', 'Agriculture'), ('rencontres', 'Rencontres E-Shelle Love'), ('njangi', 'Njangi / Tontine'), ('edu', 'Éducation'), ('promo', 'Promotions & Offres'), ('general', 'Contenu Général'), ('resto', 'Restaurants'), ('services', 'Services')], max_length=50)),
                ('facebook_post_id', models.CharField(max_length=100, unique=True, verbose_name='ID du post Facebook')),
                ('content', models.TextField(verbose_name='Contenu publié')),
                ('image_url', models.URLField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publié le')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Commentaires')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='Partages')),
                ('reach', models.PositiveIntegerField(default=0, verbose_name='Portée')),
                ('stats_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Stats mises à jour le')),
                ('page_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_posts', to='facebook_agent.facebookpageconfig')),
                ('scheduled_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published', to='facebook_agent.scheduledpost')),
            ],
            options={
                'verbose_name': 'Post Publié',
                'verbose_name_plural': 'Posts Publiés',
                'ordering': ['-published_at'],
            },
        ),
    ]
