# Generated by Django 6.0.2 on 2026-03-27 22:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_match', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('score_compatibilite', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Match',
            },
        ),
        migrations.CreateModel(
            name='PlanPremiumRencontre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20, unique=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_annuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_xaf_mensuel', models.DecimalField(decimal_places=0, default=0, help_text='Prix en FCFA (Mobile Money)', max_digits=12)),
                ('prix_xaf_annuel', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('likes_par_jour', models.IntegerField(default=10, help_text='-1 = illimité')),
                ('super_likes_par_jour', models.IntegerField(default=1)),
                ('messages_par_jour', models.IntegerField(default=20, help_text='-1 = illimité')),
                ('peut_voir_qui_a_like', models.BooleanField(default=False)),
                ('peut_rembobiner', models.BooleanField(default=False)),
                ('boost_profil_par_semaine', models.IntegerField(default=0)),
                ('photos_max', models.IntegerField(default=6)),
                ('badge_premium', models.BooleanField(default=True)),
                ('filtre_avance', models.BooleanField(default=False)),
                ('sans_publicite', models.BooleanField(default=False)),
                ('mode_incognito', models.BooleanField(default=False)),
                ('stats_profil', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Plan premium rencontre',
                'verbose_name_plural': 'Plans premium rencontre',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('dernier_message_at', models.DateTimeField(blank=True, null=True)),
                ('est_archivee', models.BooleanField(default=False)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='rencontres.match')),
            ],
            options={
                'verbose_name': 'Conversation',
                'ordering': ['-dernier_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilRencontre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_affiche', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre / Préfère ne pas préciser')], max_length=20)),
                ('orientation', models.CharField(choices=[('heterosexuel', 'Hétérosexuel(le)'), ('homosexuel', 'Homosexuel(le)'), ('bisexuel', 'Bisexuel(le)'), ('autre', 'Autre')], default='heterosexuel', max_length=20)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('origine_ethnique', models.CharField(blank=True, help_text='Ex: Bamiléké, Wolof, Yoruba, Européen, etc.', max_length=100)),
                ('nationalite', models.CharField(max_length=100)),
                ('est_diaspora', models.BooleanField(default=False)),
                ('pays_residence', models.CharField(blank=True, max_length=100)),
                ('taille_cm', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)])),
                ('morphologie', models.CharField(blank=True, choices=[('mince', 'Mince'), ('normale', 'Normale'), ('athletique', 'Athlétique'), ('ronde', 'Ronde / Enrobée'), ('grande', 'Grande')], max_length=30)),
                ('teint', models.CharField(blank=True, max_length=30)),
                ('situation_matrimoniale', models.CharField(choices=[('celibataire', 'Célibataire'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve'), ('separe', 'Séparé(e)')], max_length=30)),
                ('a_des_enfants', models.BooleanField(default=False)),
                ('nb_enfants', models.IntegerField(default=0)),
                ('veut_des_enfants', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non'), ('peut_etre', 'Peut-être'), ('deja_assez', "J'en ai déjà assez")], max_length=20)),
                ('niveau_etude', models.CharField(choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire / BAC'), ('bac2', 'BAC+2'), ('licence', 'Licence / BAC+3'), ('master', 'Master / BAC+5'), ('doctorat', 'Doctorat')], max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('revenus', models.CharField(blank=True, choices=[('modeste', 'Modeste'), ('moyen', 'Moyen'), ('confortable', 'Confortable'), ('eleve', 'Élevé'), ('prefere_pas', 'Préfère ne pas dire')], max_length=30)),
                ('religion', models.CharField(blank=True, choices=[('chretien', 'Chrétien(ne)'), ('musulman', 'Musulman(e)'), ('aucune', 'Aucune'), ('autre', 'Autre'), ('spirituel', 'Spirituel(le)')], max_length=50)),
                ('pratique_religieuse', models.CharField(blank=True, choices=[('tres_pratiquant', 'Très pratiquant(e)'), ('pratiquant', 'Pratiquant(e)'), ('peu_pratiquant', 'Peu pratiquant(e)'), ('non_pratiquant', 'Non pratiquant(e)')], max_length=20)),
                ('langues', models.JSONField(default=list, help_text="['Français', 'Anglais', 'Ewondo', ...]")),
                ('biographie', models.TextField(blank=True, max_length=1000)),
                ('ce_que_je_cherche', models.TextField(blank=True, max_length=500)),
                ('interets', models.JSONField(default=list, help_text="['Voyage', 'Cuisine', 'Sport', ...]")),
                ('recherche_age_min', models.IntegerField(default=18)),
                ('recherche_age_max', models.IntegerField(default=60)),
                ('recherche_genre', models.CharField(blank=True, max_length=20)),
                ('recherche_pays', models.JSONField(default=list)),
                ('recherche_religion', models.JSONField(default=list)),
                ('recherche_distance_km', models.IntegerField(default=500)),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to='rencontres/photos/%Y/%m/')),
                ('est_verifie', models.BooleanField(default=False)),
                ('badge_verifie', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_premium', models.BooleanField(default=False)),
                ('profil_complet', models.IntegerField(default=0, help_text='Pourcentage de complétion 0-100')),
                ('derniere_connexion', models.DateTimeField(auto_now=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('vues_profil', models.IntegerField(default=0)),
                ('afficher_en_ligne', models.BooleanField(default=True)),
                ('afficher_distance', models.BooleanField(default=True)),
                ('qui_peut_ecrire', models.CharField(choices=[('tous', 'Tout le monde'), ('matchs', 'Mes matchs uniquement'), ('premium', 'Membres premium uniquement')], default='tous', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_rencontre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil de rencontre',
                'verbose_name_plural': 'Profils de rencontre',
                'ordering': ['-derniere_connexion'],
            },
        ),
        migrations.CreateModel(
            name='PhotoProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rencontres/photos/%Y/%m/')),
                ('est_principale', models.BooleanField(default=False)),
                ('est_approuvee', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rencontres.profilrencontre')),
            ],
            options={
                'verbose_name': 'Photo de profil',
                'verbose_name_plural': 'Photos de profil',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('audio', 'Audio'), ('emoji', 'Emoji')], default='texte', max_length=20)),
                ('contenu', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rencontres/messages/%Y/%m/')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('est_supprime_expediteur', models.BooleanField(default=False)),
                ('est_supprime_destinataire', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rencontres.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='rencontres.profilrencontre')),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='profil_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_1', to='rencontres.profilrencontre'),
        ),
        migrations.AddField(
            model_name='match',
            name='profil_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_2', to='rencontres.profilrencontre'),
        ),
        migrations.CreateModel(
            name='AbonnementRencontre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('est_actif', models.BooleanField(default=True)),
                ('renouvellement_auto', models.BooleanField(default=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Référence de paiement dans billing/ ou payments/', max_length=200)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rencontres.planpremiumrencontre')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='rencontres.profilrencontre')),
            ],
            options={
                'verbose_name': 'Abonnement rencontre',
                'verbose_name_plural': 'Abonnements rencontre',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('profil_1', 'profil_2')},
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_like', models.CharField(choices=[('like', 'Like'), ('super_like', 'Super Like')], default='like', max_length=20)),
                ('date_like', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('envoyeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_envoyes', to='rencontres.profilrencontre')),
                ('recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_recus', to='rencontres.profilrencontre')),
            ],
            options={
                'verbose_name': 'Like',
                'unique_together': {('envoyeur', 'recepteur')},
            },
        ),
        migrations.CreateModel(
            name='Blocage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(blank=True, max_length=100)),
                ('date_blocage', models.DateTimeField(auto_now_add=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocages_subis', to='rencontres.profilrencontre')),
                ('bloqueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocages_effectues', to='rencontres.profilrencontre')),
            ],
            options={
                'verbose_name': 'Blocage',
                'unique_together': {('bloqueur', 'bloque')},
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('faux_profil', 'Faux profil / Usurpation'), ('harcelement', 'Harcèlement'), ('contenu_inapproprie', 'Contenu inapproprié'), ('spam', 'Spam'), ('arnaque', "Tentative d'arnaque"), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('est_traite', models.BooleanField(default=False)),
                ('action_prise', models.CharField(blank=True, choices=[('', 'En attente'), ('avertissement', 'Avertissement envoyé'), ('suspension_temp', 'Suspension temporaire'), ('suspension_def', 'Suspension définitive'), ('ignore', 'Signalement ignoré')], default='', max_length=100)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('signale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_recus', to='rencontres.profilrencontre')),
                ('signaleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_effectues', to='rencontres.profilrencontre')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_signalement'],
                'unique_together': {('signaleur', 'signale', 'raison')},
            },
        ),
    ]
