# Generated by Django 6.0.2 on 2026-04-10 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ville')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(default='🍽️', max_length=10, verbose_name='Icône (emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie alimentaire',
                'verbose_name_plural': 'Catégories alimentaires',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Quartier')),
                ('slug', models.SlugField(max_length=120)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='resto.city', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['city', 'name'],
                'unique_together': {('city', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du restaurant')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='resto/restaurants/', verbose_name='Photo de couverture')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='resto/logos/', verbose_name='Logo')),
                ('address', models.CharField(max_length=300, verbose_name='Adresse')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone (+237 6XX XX XX XX)')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp (+237 6XX XX XX XX)')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé'), ('opening_soon', 'Bientôt ouvert')], default='closed', max_length=20, verbose_name='Statut')),
                ('opening_time', models.TimeField(verbose_name="Heure d'ouverture")),
                ('closing_time', models.TimeField(verbose_name='Heure de fermeture')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='resto.foodcategory', verbose_name='Catégories')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='resto.city', verbose_name='Ville')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='resto.neighborhood', verbose_name='Quartier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-is_featured', '-views_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='resto.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Catégorie du menu',
                'verbose_name_plural': 'Catégories du menu',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du plat')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resto/dishes/', verbose_name='Photo du plat')),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('in_x_minutes', 'Disponible dans X minutes'), ('unavailable', 'Indisponible')], default='available', max_length=20, verbose_name='Disponibilité')),
                ('available_in_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Disponible dans (minutes)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Plat populaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='resto.menucategory', verbose_name='Catégorie')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='resto.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('call', 'Appel téléphonique'), ('whatsapp', 'Message WhatsApp')], max_length=20, verbose_name='Action')),
                ('session_key', models.CharField(blank=True, max_length=64, verbose_name='Session')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resto.dish', verbose_name='Plat concerné')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='resto.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free_trial', 'Essai gratuit (30 jours)'), ('basic', 'Basic'), ('premium', 'Premium')], default='free_trial', max_length=20, verbose_name='Plan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(verbose_name="Date d'expiration")),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Renouvellement auto')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='resto.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resto_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='resto.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
