# Generated by Django 6.0.2 on 2026-04-10 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Ex : Chez Mama Fouda · Yaoundé', max_length=100, verbose_name='Titre (optionnel)')),
                ('subtitle', models.CharField(blank=True, help_text='Ex : Ndolé aux crevettes — 2 500 FCFA', max_length=200, verbose_name='Sous-titre (optionnel)')),
                ('tag', models.CharField(blank=True, choices=[('', 'Aucun'), ('nouveau', 'Nouveau'), ('premium', 'Premium'), ('promo', 'Promotion'), ('vedette', 'Vedette'), ('exclusif', 'Exclusif')], help_text='Petit badge coloré affiché en haut à gauche de la bannière', max_length=20, verbose_name='Badge')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10, verbose_name='Type de média')),
                ('image', models.ImageField(blank=True, help_text='Recommandé : 1200×600px, JPG ou WebP. Max 5 Mo.', null=True, upload_to='resto/banners/', verbose_name='Image')),
                ('video', models.FileField(blank=True, help_text='Format MP4 recommandé. Max 50 Mo. Lecture auto, muette.', null=True, upload_to='resto/banners/videos/', verbose_name='Vidéo')),
                ('video_poster', models.ImageField(blank=True, help_text='Image affichée avant le chargement de la vidéo.', null=True, upload_to='resto/banners/posters/', verbose_name='Miniature vidéo')),
                ('cta_label', models.CharField(blank=True, help_text='Ex : Voir le menu · Commander maintenant', max_length=60, verbose_name='Texte du bouton CTA')),
                ('cta_url', models.CharField(blank=True, help_text='URL interne (ex: /resto/r/chez-mama-fouda/) ou externe', max_length=300, verbose_name='URL du bouton CTA')),
                ('duration', models.PositiveIntegerField(default=5, help_text='Temps avant passage automatique au slide suivant.', verbose_name="Durée d'affichage (secondes)")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(blank=True, help_text='Si renseigné, le CTA pointe automatiquement vers la page du restaurant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='resto.restaurant', verbose_name='Restaurant associé')),
            ],
            options={
                'verbose_name': 'Bannière hero',
                'verbose_name_plural': 'Bannières hero',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
