# Generated by Django 6.0.2 on 2026-04-10 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_herobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('contact_whatsapp', 'Nouveau contact WhatsApp'), ('contact_call', 'Nouveau appel'), ('new_review', 'Nouvel avis client'), ('subscription', 'Abonnement'), ('system', 'Système')], max_length=30, verbose_name='Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='resto.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Votre prénom')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note (1 à 5 étoiles)')),
                ('comment', models.TextField(help_text='Partagez votre expérience (max 800 caractères)', max_length=800, verbose_name='Votre avis')),
                ('is_approved', models.BooleanField(default=False, help_text='Seuls les avis approuvés sont visibles publiquement.', verbose_name='Approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resto.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
