# Generated by Django 6.0.2 on 2026-04-12 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icone', models.CharField(default='💊', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories de médicaments',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='QuartierPharma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='VillePharma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('region', models.CharField(default='Centre', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom générique ou commercial', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Indications, posologie générale')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pharma/medicaments/')),
                ('ordonnance', models.BooleanField(default=False, help_text='Médicament sur ordonnance uniquement')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicaments', to='pharma.categoriemedicament')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pharma/pharmacies/')),
                ('adresse', models.CharField(blank=True, max_length=250)),
                ('telephone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='Numéro sans +, ex: 237680625082', max_length=20)),
                ('whatsapp_msg', models.CharField(blank=True, max_length=300)),
                ('horaires', models.CharField(default='Lun-Sam 8h-20h', max_length=200)),
                ('garde', models.BooleanField(default=False, help_text='Pharmacie de garde (ouverte nuit/weekend)')),
                ('garde_info', models.CharField(blank=True, help_text='Ex: Garde du 12 au 15 avril', max_length=200)),
                ('livraison', models.BooleanField(default=False, help_text='Livraison à domicile disponible')),
                ('delai_livraison', models.CharField(blank=True, default='', max_length=60)),
                ('plan_actif', models.CharField(blank=True, choices=[('basic', 'Basic — 2 000 FCFA/mois'), ('pro', 'Pro — 5 000 FCFA/mois'), ('premium', 'Premium — 10 000 FCFA/mois')], max_length=10, null=True, verbose_name='Plan souscrit')),
                ('abonnement_actif', models.BooleanField(default=False, help_text='Visible sur la plateforme après paiement')),
                ('abonnement_expire_le', models.DateField(blank=True, null=True)),
                ('montant_paye', models.PositiveIntegerField(blank=True, null=True)),
                ('ref_paiement', models.CharField(blank=True, max_length=100)),
                ('notes_admin', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Activer après confirmation du paiement')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('nb_avis', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gerant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to=settings.AUTH_USER_MODEL)),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to='pharma.quartierpharma')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies', to='pharma.villepharma')),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['-is_featured', '-is_verified', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='quartierpharma',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='pharma.villepharma'),
        ),
        migrations.CreateModel(
            name='AvisPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_pharma', to=settings.AUTH_USER_MODEL)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='pharma.pharmacie')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('pharmacie', 'auteur')},
            },
        ),
        migrations.CreateModel(
            name='StockPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.PositiveIntegerField(blank=True, help_text='Prix en FCFA (laisser vide si prix variable)', null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharma.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharma.pharmacie')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['medicament__nom'],
                'unique_together': {('pharmacie', 'medicament')},
            },
        ),
    ]
