# Generated by Django 5.2.7 on 2025-11-09 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('audio', 'Audio'), ('video', 'Vidéo'), ('image', 'Image'), ('pdf', 'PDF')], max_length=10)),
                ('url', models.URLField(help_text='URL du fichier média')),
                ('lang', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('de', 'Allemand')], default='fr', max_length=2)),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Code court: tcf, tef, ielts, celpip, goethe, testdaf', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('de', 'Allemand')], help_text="Langue principale de l'examen", max_length=2)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Passage',
                'verbose_name_plural': 'Passages',
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('listening', 'Compréhension orale'), ('reading', 'Compréhension écrite'), ('writing', 'Expression écrite'), ('speaking', 'Expression orale')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('duration_sec', models.PositiveIntegerField(default=600, help_text='Durée en secondes')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='preparation_tests.exam')),
            ],
            options={
                'verbose_name': "Section d'examen",
                'verbose_name_plural': "Sections d'examen",
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(choices=[('mcq', 'QCM (choix unique)'), ('short', 'Texte court')], default='mcq', max_length=10)),
                ('stem', models.TextField(help_text='Énoncé de la question')),
                ('difficulty', models.FloatField(default=0.5, help_text='0=très facile, 1=très difficile (indicatif)')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='preparation_tests.asset')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='preparation_tests.passage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='preparation_tests.examsection')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_md', models.TextField(help_text='Explication en Markdown')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='preparation_tests.question')),
            ],
            options={
                'verbose_name': 'Explication',
                'verbose_name_plural': 'Explications',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='preparation_tests.question')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('practice', 'Entraînement'), ('mock', 'Examen blanc')], default='practice', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='preparation_tests.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_sec', models.PositiveIntegerField(default=0)),
                ('raw_score', models.FloatField(default=0.0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='preparation_tests.examsection')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='preparation_tests.session')),
            ],
            options={
                'verbose_name': 'Tentative',
                'verbose_name_plural': 'Tentatives',
                'unique_together': {('session', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='preparation_tests.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='preparation_tests.question')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
