# Generated by Django 5.2.7 on 2025-11-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('co', 'Compréhension orale'), ('ce', 'Compréhension écrite'), ('ee', 'Expression écrite'), ('eo', 'Expression orale')], max_length=2)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('locale', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('de', 'Deutsch')], default='fr', max_length=2)),
                ('content_html', models.TextField(help_text='HTML autorisé : paragraphes, listes, titres, audio, iframe.')),
                ('order', models.PositiveIntegerField(default=1, help_text='Ordre d’affichage (1=haut).')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='preparation_tests.exam')),
            ],
            options={
                'verbose_name': 'Leçon de cours',
                'verbose_name_plural': 'Leçons de cours',
                'ordering': ['exam', 'section', 'order', 'id'],
                'unique_together': {('exam', 'section', 'slug', 'locale')},
            },
        ),
    ]
