# Generated by Django 5.2.7 on 2025-11-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0002_courselesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(choices=[('TEF', 'TEF (tef)')], default='TEF', max_length=20)),
                ('section', models.CharField(choices=[('CO', 'Compréhension orale')], default='CO', max_length=5)),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'exercice")),
                ('audio', models.FileField(upload_to='tef/co/', verbose_name='Fichier audio')),
                ('question', models.TextField(verbose_name='Question principale')),
                ('option_a', models.CharField(max_length=200, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=200, verbose_name='Option B')),
                ('option_c', models.CharField(blank=True, max_length=200, verbose_name='Option C')),
                ('option_d', models.CharField(blank=True, max_length=200, verbose_name='Option D')),
                ('correct_option', models.CharField(choices=[('A', 'Réponse A'), ('B', 'Réponse B'), ('C', 'Réponse C'), ('D', 'Réponse D')], default='A', max_length=1, verbose_name='Bonne réponse')),
                ('explanation', models.TextField(blank=True, help_text="S'affiche après la validation.", verbose_name='Explication / correction')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activé pour les sessions CO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercice de compréhension orale',
                'verbose_name_plural': 'Exercices de compréhension orale',
            },
        ),
    ]
