# Generated by Django 5.2.7 on 2025-11-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0003_listeningexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='COExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='tef_co_audio/')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
