# Generated by Django 5.2.7 on 2025-11-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0004_coexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'exercice")),
                ('instruction', models.TextField(blank=True, help_text="Ce que l'apprenant doit faire.", verbose_name='Consigne')),
                ('question_text', models.TextField(help_text='Texte de la question, dialogue, énoncé…', verbose_name='Texte / question')),
                ('audio', models.FileField(blank=True, null=True, upload_to='course_exercises/audio/', verbose_name='Fichier audio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_exercises/images/', verbose_name='Image')),
                ('summary', models.TextField(blank=True, help_text="Explication affichée après l'exercice.", verbose_name='Résumé / correction')),
                ('order', models.PositiveIntegerField(default=1, help_text='Ordre d’affichage dans la leçon (1=haut).')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='preparation_tests.courselesson', verbose_name='Leçon')),
                ('passage', models.ForeignKey(blank=True, help_text='Texte support si nécessaire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_exercises', to='preparation_tests.passage', verbose_name='Passage lié')),
            ],
            options={
                'verbose_name': 'Exercice de cours',
                'verbose_name_plural': 'Exercices de cours',
                'ordering': ['lesson', 'order', 'id'],
            },
        ),
    ]
