# Generated by Django 5.2.7 on 2025-11-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0005_courseexercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COExercise',
        ),
        migrations.DeleteModel(
            name='ListeningExercise',
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Lettre de la bonne réponse (A, B, C, D). Laisser vide pour une question ouverte.', max_length=1, verbose_name='Bonne réponse'),
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, verbose_name='Option A'),
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, verbose_name='Option B'),
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, verbose_name='Option C'),
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, verbose_name='Option D'),
        ),
    ]
