# Generated by Django 5.2.7 on 2025-12-15 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0007_exam_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courseexercise',
            options={'ordering': ['lesson', 'order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='courselesson',
            options={'ordering': ['exam', 'section', 'order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='courselesson',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='elapsed_sec',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='courseexercise',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='course_exercises/audio/'),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_exercises/images/'),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='preparation_tests.courselesson'),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='option_a',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='option_b',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='option_c',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='option_d',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preparation_tests.passage'),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='content_html',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='examsection',
            name='code',
            field=models.CharField(choices=[('co', 'Compréhension orale'), ('ce', 'Compréhension écrite'), ('ee', 'Expression écrite'), ('eo', 'Expression orale')], max_length=2),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='text_md',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.FloatField(default=0.5, help_text='0=très facile, 1=très difficile'),
        ),
    ]
