# Generated by Django 5.2.7 on 2025-12-16 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0008_alter_answer_options_alter_attempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examsection',
            options={'ordering': ['exam', 'order']},
        ),
        migrations.AlterModelOptions(
            name='explanation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='passage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.RemoveField(
            model_name='courseexercise',
            name='passage',
        ),
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparation_tests.attempt'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparation_tests.question'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparation_tests.examsection'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparation_tests.session'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('de', 'Allemand')], max_length=2),
        ),
        migrations.AlterField(
            model_name='examsection',
            name='duration_sec',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='question',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preparation_tests.asset'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preparation_tests.passage'),
        ),
        migrations.AlterField(
            model_name='question',
            name='stem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='subtype',
            field=models.CharField(choices=[('mcq', 'QCM'), ('short', 'Texte court')], default='mcq', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparation_tests.exam'),
        ),
    ]
