# Generated by Django 5.2.7 on 2025-12-16 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0009_alter_asset_options_alter_choice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(max_length=20)),
                ('skill', models.CharField(choices=[('co', 'Compréhension orale'), ('ce', 'Compréhension écrite'), ('ee', 'Expression écrite'), ('eo', 'Expression orale')], max_length=2)),
                ('score_percent', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exam_code', 'skill')},
            },
        ),
    ]
