# Generated by Django 5.2.7 on 2025-12-16 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0010_userskillprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkillResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(choices=[('tef', 'TEF'), ('tcf', 'TCF')], max_length=10)),
                ('skill', models.CharField(choices=[('co', 'Compréhension orale'), ('ce', 'Compréhension écrite'), ('ee', 'Expression écrite'), ('eo', 'Expression orale')], max_length=2)),
                ('session_type', models.CharField(choices=[('training', 'Entraînement'), ('mock', 'Examen blanc')], max_length=10)),
                ('score_percent', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
