# Generated by Django 5.2.7 on 2025-12-16 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0011_userskillresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='url',
        ),
        migrations.AddField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='kind',
            field=models.CharField(choices=[('audio', 'Audio'), ('image', 'Image'), ('video', 'Video')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='lang',
            field=models.CharField(default='fr', max_length=10),
        ),
    ]
