# Generated by Django 5.2.7 on 2025-12-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0012_remove_asset_url_asset_created_at_asset_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselesson',
            options={'ordering': ['exam', 'level', 'section', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='courselesson',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, default='A2', max_length=2),
        ),
        migrations.AlterField(
            model_name='userskillresult',
            name='exam_code',
            field=models.CharField(max_length=20),
        ),
    ]
