# Generated by Django 5.2.7 on 2025-12-20 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0016_studyplanprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cefrcertificate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courseexercise',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examsection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userlessonprogress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userskillresult',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cefrcertificate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userskillprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='courseexercise',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='courseexercise',
            name='image',
        ),
        migrations.RemoveField(
            model_name='courseexercise',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='courseexercise',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='courseexercise',
            name='title',
        ),
        migrations.RemoveField(
            model_name='studyplanprogress',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='userskillresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userskillresult',
            name='session_type',
        ),
        migrations.AddField(
            model_name='studyplanprogress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studyplanprogress',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='preparation_tests.attempt'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='raw_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='preparation_tests.session'),
        ),
        migrations.AlterField(
            model_name='cefrcertificate',
            name='certificate_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='cefrcertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='correct_option',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preparation_tests.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='subtype',
            field=models.CharField(choices=[('mcq', 'Choix multiple'), ('text', 'Texte libre'), ('audio', 'Audio')], default='mcq', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.CharField(choices=[('practice', 'Entraînement'), ('mock', 'Examen blanc')], max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyplanprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparation_tests.courselesson'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userskillprogress',
            name='skill',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='userskillprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userskillresult',
            name='skill',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='userskillresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='userskillprogress',
            name='total_attempts',
        ),
        migrations.RemoveField(
            model_name='userskillprogress',
            name='updated_at',
        ),
    ]
