# Generated by Django 5.2.7 on 2025-12-20 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0017_alter_cefrcertificate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselesson',
            options={'ordering': ['order'], 'verbose_name': 'Leçon', 'verbose_name_plural': 'Leçons'},
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_audios', to='preparation_tests.asset'),
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_images', to='preparation_tests.asset'),
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='title',
            field=models.CharField(default='Exercice', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courselesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='option_a',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='option_b',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='preparation_tests.exam'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='locale',
            field=models.CharField(default='fr', max_length=5),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='section',
            field=models.CharField(choices=[('co', 'Compréhension Orale'), ('ce', 'Compréhension Écrite'), ('ee', 'Expression Écrite'), ('eo', 'Expression Orale')], max_length=2),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='preparation_tests.courselesson'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
