# Generated by Django 5.2.7 on 2025-12-21 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0018_alter_courselesson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskillresult',
            name='exam_code',
        ),
        migrations.RemoveField(
            model_name='userskillresult',
            name='skill',
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userskillresult',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preparation_tests.exam'),
        ),
        migrations.AddField(
            model_name='userskillresult',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preparation_tests.examsection'),
        ),
    ]
