# Generated by Django 5.2.7 on 2025-12-21 22:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0019_remove_userskillresult_exam_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cefrcertificate',
            name='certificate_id',
        ),
        migrations.AddField(
            model_name='cefrcertificate',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
