# Generated by Django 5.2.7 on 2025-12-27 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0022_coachiareport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselesson',
            options={'ordering': ['level', 'order'], 'verbose_name': 'Leçon', 'verbose_name_plural': 'Leçons'},
        ),
        migrations.AddField(
            model_name='courselesson',
            name='exams',
            field=models.ManyToManyField(blank=True, help_text='Examens utilisant cette leçon (TEF, TCF, DELF, DALF)', related_name='lessons', to='preparation_tests.exam'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_lessons', to='preparation_tests.exam'),
        ),
    ]
