# Generated by Django 5.2.7 on 2026-02-18 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0023_alter_courselesson_options_courselesson_exams_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_answer', models.CharField(blank=True, default='', max_length=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparation_tests.courseexercise')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparation_tests.courselesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'lesson'], name='preparation_user_id_d78514_idx'), models.Index(fields=['user', 'exercise'], name='preparation_user_id_bcf4e0_idx')],
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
