# Generated by Django 5.2.7 on 2026-02-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0024_userexerciseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplanprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userskillprogress',
            name='current_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2),
        ),
        migrations.AddField(
            model_name='userskillprogress',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
