# Generated by Django 5.2.7 on 2026-02-28 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0026_eesubmission_eosubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=2)),
                ('score_co', models.PositiveIntegerField(blank=True, null=True)),
                ('score_ce', models.PositiveIntegerField(blank=True, null=True)),
                ('score_global', models.PositiveIntegerField(blank=True, null=True)),
                ('co_correct', models.PositiveIntegerField(default=0)),
                ('co_total', models.PositiveIntegerField(default=0)),
                ('ce_correct', models.PositiveIntegerField(default=0)),
                ('ce_total', models.PositiveIntegerField(default=0)),
                ('cefr_estimate', models.CharField(blank=True, max_length=10)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Résultat examen blanc',
                'verbose_name_plural': 'Résultats examens blancs',
                'ordering': ['-taken_at'],
            },
        ),
    ]
