# Generated by Django 5.2.7 on 2026-03-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0026_examformatresult'),
        ('preparation_tests', '0027_mockexamresult'),
    ]

    operations = [
    ]
