# Generated by Django 6.0.2 on 2026-03-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_tests', '0028_merge_0026_examformatresult_0027_mockexamresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskillprogress',
            name='current_level',
            field=models.CharField(choices=[('A1', 'A1 — Débutant'), ('A2', 'A2 — Élémentaire'), ('B1', 'B1 — Intermédiaire'), ('B2', 'B2 — Intermédiaire supérieur'), ('C1', 'C1 — Avancé'), ('C2', 'C2 — Maîtrise')], default='A1', max_length=2),
        ),
    ]
