# Generated by Django 6.0.2 on 2026-03-21 16:17

import boutique.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icone', models.CharField(default='📦', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie produit',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('payee', 'Payée'), ('livree', 'Livrée / Téléchargée'), ('remboursee', 'Remboursée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('email_acheteur', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Pour les non-connectés', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('description_courte', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=boutique.models.thumbnail_upload_path)),
                ('fichier', models.FileField(blank=True, help_text='Fichier digital (zip, pdf, etc.)', null=True, upload_to=boutique.models.produit_upload_path)),
                ('url_externe', models.URLField(blank=True, help_text='Lien externe si fichier hébergé ailleurs')),
                ('type_produit', models.CharField(choices=[('template', 'Template / Thème'), ('ebook', 'Ebook / PDF'), ('outil', 'Outil / Logiciel'), ('plugin', 'Plugin / Extension'), ('pack_ia', 'Pack IA'), ('cours', 'Cours standalone'), ('autre', 'Autre')], default='template', max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, default=0, help_text='Prix en FCFA', max_digits=10)),
                ('prix_barre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_gratuit', models.BooleanField(default=False)),
                ('nb_ventes', models.PositiveIntegerField(default=0)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('nb_avis', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='boutique.categorieproduit')),
                ('vendeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_vendus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='boutique.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boutique.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='boutique/galerie/')),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boutique.produit')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Telechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nb_telechargements', models.PositiveIntegerField(default=0)),
                ('max_telechargements', models.PositiveIntegerField(default=5)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Téléchargement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='boutique.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit')),
            ],
            options={
                'unique_together': {('panier', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='AvisProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='boutique.produit')),
            ],
            options={
                'verbose_name': 'Avis produit',
                'ordering': ['-created_at'],
                'unique_together': {('utilisateur', 'produit')},
            },
        ),
    ]
