# Generated by Django 6.0.2 on 2026-03-21 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icone', models.CharField(default='📚', help_text='Emoji', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('description_courte', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='formations/thumbnails/')),
                ('video_intro', models.URLField(blank=True)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('tous_niveaux', 'Tous niveaux')], default='debutant', max_length=20)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('bi', 'Bilingue')], default='fr', max_length=5)),
                ('prix', models.DecimalField(decimal_places=2, default=0, help_text='Prix en FCFA (0 = gratuit)', max_digits=10)),
                ('prix_barre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('nb_lecons', models.PositiveIntegerField(default=0)),
                ('duree_totale', models.PositiveIntegerField(default=0, help_text='Durée en minutes')),
                ('nb_inscrits', models.PositiveIntegerField(default=0)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('objectifs', models.JSONField(blank=True, default=list)),
                ('prerequis', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formations', to='formations.categorie')),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formations_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='formations.formation')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'ordering': ['formation', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_unique', models.CharField(max_length=40, unique=True)),
                ('date_obtenu', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='certificats/')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
            options={
                'verbose_name': 'Certificat',
                'ordering': ['-date_obtenu'],
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_lecon', models.CharField(choices=[('video', 'Vidéo'), ('texte', 'Texte / Article'), ('quiz', 'Quiz'), ('tp', 'Travaux pratiques'), ('pdf', 'Document PDF')], default='texte', max_length=10)),
                ('contenu', models.TextField(help_text='Contenu HTML riche')),
                ('video_url', models.URLField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='formations/pdfs/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('duree', models.PositiveIntegerField(default=5, help_text='Durée estimée en minutes')),
                ('is_free', models.BooleanField(default=False, help_text='Accessible sans inscription')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='formations.chapitre')),
            ],
            options={
                'verbose_name': 'Leçon',
                'ordering': ['chapitre', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('score_min', models.PositiveIntegerField(default=70, help_text='Score minimum pour réussir (%)')),
                ('duree_min', models.PositiveIntegerField(default=0, help_text='Durée limite en minutes (0 = illimité)')),
                ('actif', models.BooleanField(default=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_finaux', to='formations.formation')),
                ('lecon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='formations.lecon')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('type_q', models.CharField(choices=[('qcm', 'QCM (choix multiple)'), ('vf', 'Vrai / Faux'), ('courte', 'Réponse courte'), ('longue', 'Réponse longue')], default='qcm', max_length=10)),
                ('choix', models.JSONField(blank=True, default=list)),
                ('reponse_correcte', models.TextField(blank=True)),
                ('explication', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='formations.quiz')),
            ],
            options={
                'ordering': ['quiz', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ResultatQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, help_text='Score en %')),
                ('nb_bonnes', models.PositiveIntegerField(default=0)),
                ('nb_questions', models.PositiveIntegerField(default=0)),
                ('reponses', models.JSONField(blank=True, default=dict)),
                ('termine', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.quiz')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvisFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='formations.formation')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('utilisateur', 'formation')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('progression_pct', models.PositiveIntegerField(default=0)),
                ('termine', models.BooleanField(default=False)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formations.formation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription',
                'ordering': ['-date_inscription'],
                'unique_together': {('utilisateur', 'formation')},
            },
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completee', models.BooleanField(default=False)),
                ('temps_passe', models.PositiveIntegerField(default=0, help_text='Temps passé en secondes')),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='formations.lecon')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_lecons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'lecon')},
            },
        ),
    ]
