# Generated by Django 6.0.2 on 2026-05-17 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], db_index=True, max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'En file'), ('SENT', 'Envoyee'), ('FAILED', 'Echouee')], db_index=True, default='QUEUED', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tchaslucpay_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal notification',
                'verbose_name_plural': 'Journal notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
