# Generated by Django 6.0.2 on 2026-05-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tchaslucpay_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'En file'), ('SENT', 'Envoyee'), ('FAILED', 'Echouee'), ('ECHEC', 'Echec')], db_index=True, default='QUEUED', max_length=20),
        ),
    ]
